class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'uz': {
      'select_language': 'Tilni tanlang',
      'who_are_you': 'Siz kimsiz?',
      'select_role': 'Rolingizni tanlang',
      'client': 'Yuk beruvchi',
      'client_subtitle': 'Yuk tashish uchun buyurtma beraman',
      'driver': 'Haydovchi',
      'driver_subtitle': 'Yuk tashib daromad qilaman',
      'phone_title': 'Telefon raqamingiz',
      'phone_subtitle': 'SMS orqali tasdiqlash kodi yuboramiz',
      'send_code': 'Kodni yuborish',
      'enter_code': 'Kodni kiriting',
      'code_sent': 'raqamiga kod yuborildi',
      'verify': 'Tasdiqlash',
      'resend': 'Qayta yuborish',
      'resend_in': 'Qayta yuborish:',
      'skip': 'O\'tkazib yuborish',
      'next': 'Keyingi',
      'start': 'Boshlash',
      'home': 'Bosh',
      'orders': 'Buyurtmalar',
      'wallet': 'Hamyon',
      'profile': 'Profil',
      'settings': 'Sozlamalar',
      'notifications': 'Bildirishnomalar',
      'where_to': 'Qayerga yuk tashlaysiz?',
      'saved_places': 'Saqlangan manzillar',
      'tariffs': 'Tariflar',
      'full_name': 'To\'liq ism',
      'passport': 'Pasport',
      'license': 'Haydovchilik guvohnomasi',
      'tech_passport': 'Texnik pasport',
      'truck_type': 'Mashina turi',
      'plate_number': 'Davlat raqami',
      'capacity': 'Yuk ko\'tarish sig\'imi',
      'continue_btn': 'Davom etish',
      'pending_title': 'Ma\'lumotlaringiz qabul qilindi!',
      'pending_subtitle': 'Admin ko\'rib chiqib tasdiqlaydi. Bu biroz vaqt olishi mumkin.',
      'waiting': 'Kutilmoqda...',
      'onboarding1_title': 'Yuk tashish oson!',
      'onboarding1_subtitle': 'Istalgan shahardan istalgan shaharga yuk tashlang.',
      'onboarding2_title': 'Real vaqt kuzatuv',
      'onboarding2_subtitle': 'Yuk harakati xaritada real vaqtda kuzating.',
      'onboarding3_title': 'Qulay to\'lov',
      'onboarding3_subtitle': 'Hamyon orqali tez va xavfsiz to\'lov.',
      'step_sent': 'Hujjatlar yuborildi',
      'step_reviewing': 'Admin ko\'rib chiqmoqda',
      'step_approved': 'Tasdiqlash',
      'pending_time': 'Javob 5-20 daqiqa ichida beriladi',
      'edit_profile': 'Profilni tahrirlash',
      'edit': 'Tahrirlash',
      'save': 'Saqlash',
      'cancel': 'Bekor qilish',
      'close': 'Yopish',
      'confirm': 'Tasdiqlash',
      'apply': 'Qo\'llash',
      'name': 'Ism',
      'vehicle_info': 'Mashina ma\'lumotlari',
      'vehicle_edit': 'Mashina ma\'lumotlarini tahrirlash',
      'vehicle_edit_warning': 'Xavfsizlik uchun admin tasdiqlashi kerak',
      'verification_info': 'Tasdiqlanish ma\'lumotlari',
      'admin_approval_required': 'Admin tasdiqlashi talab etiladi',
      'admin_approval_sent': 'So\'rov yuborildi! Admin tasdiqlashini kuting.',
      'admin_approval_notice': 'Siz tasdiqlanish ma\'lumotlarini o\'zgartirdingiz. Xavfsizlik uchun admin tasdiqlashini kuting.',
      'change_plate': 'Davlat raqamini o\'zgartirish',
      'change_plate_subtitle': 'Yangi davlat raqami va texnik pasport talab qilinadi',
      'new_plate': 'Yangi davlat raqami',
      'upload_tech_passport': 'Texnik pasportni yuklang',
      'request_sent': 'So\'rov yuborildi',
      'request_pending': 'Admin ko\'rib chiqmoqda',
      'change_truck': 'Mashina turini o\'zgartirish',
      'documents': 'Hujjatlar',
      'uploaded': 'Yuklangan',
      'not_uploaded': 'Yuklanmagan',
      'tap_to_upload': 'Yuklash uchun bosing',
      'tap_to_change': 'O\'zgartirish uchun bosing',
      'language': 'Til',
      'theme': 'Tema',
      'select_theme': 'Temani tanlang',
      'theme_auto': 'Avto',
      'theme_light': 'Yorug\'',
      'theme_dark': 'Qorong\'u',
      'logout': 'Chiqish',
      'terms': 'Oferta shartlari',
      'personal_info': 'Shaxsiy ma\'lumotlar',
      'app_settings': 'Ilova sozlamalari',
      'app_tagline': 'Yuk tashish platformasi',
      'change_password': 'Parolni o\'zgartirish',
      'current_password': 'Joriy parol',
      'new_password': 'Yangi parol',
      'confirm_password': 'Parolni tasdiqlang',
      'change_phone': 'Telefon raqamni o\'zgartirish',
      'phone_number_label': 'Telefon raqami',
      'current_phone_number': 'Joriy telefon raqam',
      'connected_phone_title': 'Hisobingizga ulangan raqam',
      'change_phone_button': 'Telefon raqamni o\'zgartirish',
      'resend_code': 'Kodni qayta yuborish',
      'new_phone_number': 'Yangi telefon raqam',
      'phone_already_registered_hint': '',
      'phone_change_otp_sent': 'Kod {phone} raqamiga yuborildi',
      'phone_changed_success': 'Telefon raqam muvaffaqiyatli o\'zgartirildi!',
      'enter_new_phone_hint': 'Yangi raqamingizni kiriting',
      'forgot_password': 'Parolni unutdingizmi?',
      'password_changed': 'Parol muvaffaqiyatli o\'zgartirildi',
      'password_mismatch': 'Parollar mos kelmaydi',
      'password_too_short': 'Parol kamida 6 ta belgidan iborat bo\'lishi kerak',
      'otp_sent': 'OTP kod yuborildi',
      'enter_otp': 'OTP kodni kiriting',
      'otp_invalid_error': 'OTP kod noto\'g\'ri yoki muddati o\'tgan',
      'set_new_password': 'Yangi parol o\'rnating',
      'reset_password': 'Parolni tiklash',
      'reset_password_subtitle': 'Telefon raqamingizga tasdiqlash kodi yuboramiz',
      'reset_password_phone_prompt': 'Telefon raqamingizni kiriting, OTP yuboramiz',
      'phone_incomplete_error': 'Telefon raqamni to\'liq kiriting',
      'reset_password_otp_note': 'Muhim: yuboribgan OTP kodni endi tasdiqlab, yangi parolni saqlaymiz.',
      'password_field_hint': 'Parol',
      'enter_password_error': 'Parolni kiriting',
      'invalid_credentials': 'Telefon raqam yoki parol noto\'g\'ri',
      'no_account_question': 'Hisobingiz yo\'qmi?',
      'create_new_account': 'Yangi hisob yaratish',
      'invalid_or_expired_code': 'Kod noto\'g\'ri yoki eskirgan. Qaytadan urinib ko\'ring.',
      'set_new_password_subtitle': 'Kamida 6 ta belgidan iborat yangi parol o\'rnating',
      // ==== Client Home ====
      'menu': 'Menyu',
      'my_orders': 'Buyurtmalarim',
      'enter_address': 'Manzil kiriting',
      'place_order': 'Buyurtma berish',
      'cancel_selection': 'Bekor qilish',
      'from_question': 'Qayerdan?',
      'to_question': 'Qayerga?',
      'select_vehicle': 'Mashina turini tanlang',
      'select_vehicle_hint': 'Mashina turini tanlang',
      'select_button': 'Tanlash',
      'vehicle_help_text': 'Yukingiz hajmiga mos mashina turini tanlang',
      'select_truck_error': 'Iltimos, mashina turini tanlang',
      'select_truck_first_warning': 'Avval mashina turini tanlang',
      'weight_tons': 'Yuk og\'irligi (tonna)',
      'enter_weight_error': 'Og\'irlikni kiriting',
      'select_weight_hint': 'Og\'irlikni tanlang',
      'weight_help_text': 'Yukingizning taxminiy og\'irligini tonnada tanlang',
      'auto_calculated_hint': 'Masofa avtomatik hisoblanadi',
      'cargo_type_hint': 'Yuk turini kiriting (masalan: mebel, oziq-ovqat)',
      'enter_cargo_type_error': 'Yuk turini kiriting',
      'order_when_label': 'Qachon?',
      'select_time_hint': 'Vaqtni tanlang',
      'select_time_error': 'Vaqtni tanlang',
      'estimated_price_label': 'Taxminiy narx',
      'note_optional': 'Izoh (ixtiyoriy)',
      'generic_error': 'Xatolik yuz berdi',
      'error_timeout': 'Server javob bermadi. Birozdan so\'ng qayta urinib ko\'ring.',
      'error_no_connection': 'Internet aloqasi yo\'q. Aloqani tekshirib, qayta urinib ko\'ring.',
      'error_server': 'Serverda xatolik yuz berdi. Birozdan so\'ng qayta urinib ko\'ring.',
      'no_internet_title': 'Internet aloqasi yo\'q',
      'no_internet_subtitle': 'Iltimos, internet aloqangizni tekshiring va qayta urinib ko\'ring',
      'retry_connection': 'Qayta urinib ko\'rish',
      'searching_driver': 'Haydovchi qidirilmoqda...',
      'cancel_search': 'Bekor qilish',
      'driver_assigned': 'Haydovchi tayinlandi',
      'driver_arriving': 'Haydovchi kelmoqda',
      'loading_cargo': 'Yuk yuklanmoqda',
      'in_transit': 'Yuk yo\'lda',
      'delivered_msg': 'Yetkazildi! 🎉',
      'order_active': 'Buyurtma faol',
      'complete_order': 'Yakunlash',
      'select_btn': 'Tanlang',
      'route_time_min': 'daqiqa',
      'route_time_hour': 'soat',
      'current_location_label': 'Joriy manzil',
      'order_details': 'Tafsilotlar',
      'vehicle_type_label': 'Mashina turi',
      'weight_label': 'Yuk og\'irligi',
      'price_label': 'Taxminiy narx',
      'price_not_set': 'Hali aniqlanmagan',
      'note_label': 'Izoh',
      'arriving_in': 'yetib keladi',
      'location_permission_denied': 'Joylashuv ruxsati berilmagan — manzilni qo\'lda tanlang',
      // ==== Client Home: alohida sahifalar (manzil/buyurtma/aktiv buyurtma) ====
      'select_address_title': 'Manzil tanlash',
      'no_results_found': 'Natija topilmadi',
      'map_btn_label': 'Xarita',
      'confirm_address_btn': 'Manzilni tasdiqlash',
      'search_address_hint': 'Manzil qidirish...',
      'selected_address_label': 'Tanlangan manzil',
      'resolving_label': 'Aniqlanmoqda...',
      'address_not_found': 'Manzil topilmadi',
      'order_details_page_title': 'Buyurtma tafsilotlari',
      'active_order_title': 'Faol buyurtma',
      'route_label': 'Marshrut',
      // ==== Faol buyurtma sahifasi (qayta dizayn) ====
      'live_label': 'LIVE',
      'route_summary_label': 'Marshrut xulosasi',
      'load_weight_label': 'Yuk og\'irligi',
      'cargo_type_label': 'Yuk turi',
      'arrived_at_label': 'Yetib keldi',
      'est_label': 'Taxminan',
      'estimated_arrival_label': 'Taxminiy yetib kelish: {min} daqiqada',
      'traffic_light': 'Yengil tirbandlik',
      'traffic_moderate': 'O\'rtacha tirbandlik',
      'traffic_heavy': 'Zich tirbandlik',
      'turn_left_hint': '{dist}dan keyin chapga buriling',
      'turn_right_hint': '{dist}dan keyin o\'ngga buriling',
      'turn_straight_hint': '{dist}dan keyin to\'g\'ri yuring',
      'pickup_label': 'OLIB KETISH',
      'dropoff_label': 'YETKAZISH',
      'emergency_support_label': 'Favqulodda yordam',
      // ==== Menu (toggle) modali ====
      'active_order': 'Faol buyurtma',
      'active_order_subtitle': 'Joriy buyurtmangizni kuzating',
      'my_orders_subtitle': 'Barcha buyurtmalaringiz',
      'notifications_subtitle': 'Yangiliklar va bildirishnomalar',
      'profile_subtitle': 'Shaxsiy ma\'lumotlar',
      'language_subtitle': 'Ilova tilini tanlang',
      'theme_subtitle': 'Ko\'rinishni sozlang',
      'wallet_subtitle': 'Balans va tranzaksiyalar',
      'order_history_subtitle': 'Yakunlangan buyurtmalar',
      // ==== Saqlangan manzillar ====
      'saved_places_subtitle': 'Tez-tez ishlatiladigan manzillar',
      'no_saved_addresses': 'Hali saqlangan manzil yo\'q',
      'add_new_address': 'Yangi manzil qo\'shish',
      'edit_address': 'Manzilni tahrirlash',
      'add_address_title': 'Manzil qo\'shish',
      'delete': 'O\'chirish',
      'delete_address_confirm_title': 'Manzilni o\'chirish',
      'delete_address_confirm_msg': 'Bu manzilni o\'chirishni tasdiqlaysizmi?',
      'address_name_optional_hint': 'Nom (ixtiyoriy)',
      'address_field_hint': 'Manzil qidiring yoki xaritadan tanlang',
      'choose_on_map': 'Xaritadan tanlash',
      'address_saved_snackbar': 'Manzil saqlandi',
      'address_updated_snackbar': 'Manzil yangilandi',
      'address_deleted_snackbar': 'Manzil o\'chirildi',
      'quick_save_address_title': 'Manzilni saqlash',
      // ==== Driver Home ====
      'online': 'Online',
      'offline': 'Offline',
      'order_waiting': 'Buyurtma kutilmoqda',
      'you_are_online': 'Siz onlinesiz, buyurtma kelishini kuting',
      'you_are_offline': 'Siz offlainesiz',
      'auto_offline_notice': 'Siz avtomatik offline bo\'lib qoldingiz (GPS signal yo\'qolgani sababli). Davom etish uchun qayta Online bo\'ling.',
      'gps_service_disabled_notice': 'GPS xizmati o\'chirilgan. Joylashuvni aniqlash uchun uni telefon sozlamalaridan yoqing.',
      'go_online_hint': 'Buyurtma olish uchun onlayn bo\'ling',
      'go_online': 'Online bo\'lish',
      'new_order_label': 'YANGI BUYURTMA',
      'accept_order': 'Qabul qilish',
      'reject_order': 'Rad etish',
      'slide_to_accept': 'Qabul qilish uchun suring',
      'going_to_client': 'Mijozga bormoqda',
      'cargo_on_way': 'Yuk yo\'lda',
      'picked_up_continue': 'Yuk olindi — yo\'lga chiqish',
      'delivered_finish': 'Yetkazildi — yakunlash',
      // ==== Driver History ====
      'view_all_history': 'Barchasini ko\'rish',
      'order_history_title': 'Buyurtmalar tarixi',
      'order_history_full_title': 'Barcha buyurtmalar',
      'filter_all': 'Barchasi',
      'filter_active_only': 'Faqat faol',
      'filter_inactive_only': 'Faqat faol emas',
      'filter_delivered': 'Yetkazilgan',
      'filter_cancelled': 'Bekor qilingan',
      'search_city_hint': 'Shahar bo\'yicha qidirish...',
      'no_orders_found': 'Buyurtmalar topilmadi',
      'today': 'Bugun',
      'yesterday': 'Kecha',
      'status_searching': 'Haydovchi qidirilmoqda',
      'status_offered': 'Taklif yuborilgan',
      'status_accepted': 'Qabul qilindi',
      'status_driver_arriving': 'Haydovchi kelmoqda',
      'status_loading': 'Yuklanmoqda',
      'status_in_transit': 'Yo\'lda',
      'status_delivered': 'Yetkazildi',
      'status_completed': 'Yakunlandi',
      'status_cancelled': 'Bekor qilindi',
      // ==== Buyurtma tafsiloti (tarix, faqat o'qish) ====
      'status_history_label': 'Status tarixi',
      'sos_sent_label': 'SOS signal yuborilgan',
      'additional_info_label': 'Qo\'shimcha ma\'lumot',
      'distance_traveled_label': 'Bosib o\'tilgan masofa',
      'completion_duration_label': 'Yakunlanish vaqti',
      'client_rating_label': 'Mijoz bahosi',
      // ==== Buyurtmalar tarixi (qayta dizayn) ====
      'trip_label': 'Reys',
      'from_label': 'Qayerdan',
      'to_label': 'Qayerga',
      'filter_pending': 'Kutilmoqda',
      'month_01': 'Yanvar',
      'month_02': 'Fevral',
      'month_03': 'Mart',
      'month_04': 'Aprel',
      'month_05': 'May',
      'month_06': 'Iyun',
      'month_07': 'Iyul',
      'month_08': 'Avgust',
      'month_09': 'Sentabr',
      'month_10': 'Oktabr',
      'month_11': 'Noyabr',
      'month_12': 'Dekabr',
      'month_short_01': 'yan',
      'month_short_02': 'fev',
      'month_short_03': 'mar',
      'month_short_04': 'apr',
      'month_short_05': 'may',
      'month_short_06': 'iyun',
      'month_short_07': 'iyul',
      'month_short_08': 'avg',
      'month_short_09': 'sen',
      'month_short_10': 'okt',
      'month_short_11': 'noy',
      'month_short_12': 'dek',
      'other_date_label': 'Boshqa',
      // ==== Qo'ng'iroq / Bekor qilish / Avatar ====
      'call': 'Qo\'ng\'iroq qilish',
      'call_confirm_title': 'Qo\'ng\'iroq qilasizmi?',
      'call_confirm_message': 'Ushbu raqamga qo\'ng\'iroq qilinsinmi?',
      'call_failed': 'Qo\'ng\'iroq qilib bo\'lmadi',
      'cancel_order_title': 'Buyurtmani bekor qilish',
      'cancel_order_message': 'Buyurtmani bekor qilmoqchimisiz? Bu sizning reytingingizga ta\'sir qilishi mumkin.',
      'yes_cancel_order': 'Ha, bekor qilish',
      'no_keep_order': 'Yo\'q',
      'order_cancelled': 'Buyurtma bekor qilindi',
      'logout_confirm_title': 'Chiqish',
      'logout_confirm_message': 'Tizimdan chiqmoqchimisiz?',
      'confirm_logout': 'Ha, chiqish',
      'profile_photo_optional': 'Profil rasmi (ixtiyoriy)',
      'profile_photo_hint': 'Bu majburiy emas, agar yuklamasangiz standart rasm ishlatiladi',
      // ==== Hamyon (Wallet) ====
      'main_balance': 'Asosiy balans',
      'total_trips': 'Jami reyslar',
      'total_earned': 'Jami daromad',
      'topup_balance': 'Balans to\'ldirish',
      'topup_requests_history': 'To\'ldirish so\'rovlarim tarixi',
      'recent_transactions': 'So\'nggi tranzaksiyalar',
      'view_all': 'Barchasini ko\'rish',
      'no_transactions': 'Tranzaksiyalar yo\'q',
      'card_number_copied': 'Karta raqami nusxalandi!',
      'topup_card_label': 'Pul o\'tkaziladigan karta:',
      'copy_label': 'Nusxa',
      'topup_card_hint': 'Ushbu karta raqamini nusxalab, Click yoki Payme orqali to\'lov qiling, so\'ng chekini yuklang.',
      'no_active_card': 'Hozirda aktiv to\'lov kartasi yo\'q.',
      'topup_amount_label': 'To\'lov summasi (so\'m)',
      'topup_amount_note': 'Tashlagan summangizni to\'liq va to\'g\'ri kiriting. Chek bilan bir xil bo\'lsin.',
      'receipt_uploaded': 'Chek yuklandi ✓',
      'receipt_upload_prompt': 'Chek rasmini yuklang',
      'receipt_upload_hint': 'Chek rasmini galereyadan tanlang. Aniq va o\'qilishi mumkin bo\'lsin.',
      'topup_amount_error': 'To\'g\'ri summa kiriting',
      'receipt_required_error': 'Chek rasmini yuklang',
      'topup_generic_error': 'Xatolik yuz berdi. Qayta urinib ko\'ring.',
      'no_card_label': 'Karta yo\'q',
      'submit_label': 'Jo\'natish',
      'topup_request_sent': 'So\'rov yuborildi!',
      'topup_pending_note': 'Admin tasdiqlashini kuting.\nOdatda 5-30 daqiqa ichida balansga qo\'shiladi.',
      'topup_history_title': 'So\'rovlarim tarixi',
      'topup_filter_all': 'Barchasi',
      'topup_status_pending': 'Kutilmoqda',
      'topup_status_approved': 'Tasdiqlangan',
      'topup_status_rejected': 'Rad etilgan',
      'topup_no_requests_found': 'So\'rovlar topilmadi',
      'topup_request_date': 'So\'rov sanasi',
      'topup_approved_amount': 'Tasdiqlangan summa',
      'topup_rejection_reason': 'Rad etilish sababi',
      'topup_receipt_label': 'Yuklangan chek',
      'transaction_history_title': 'Tranzaksiyalar tarixi',
      'search_placeholder': 'Qidirish...',
      'no_transactions_found': 'Tranzaksiyalar topilmadi',
      // ==== Baholash oynasi (rating_dialog) ====
      'rating_dialog_title': 'Yetkazib berish qanday bo\'ldi?',
      'rating_dialog_subtitle': 'Sizning fikringiz GoWay xizmat sifatini yaxshilashga yordam beradi',
      'review_placeholder': 'Sharh yozing...',
      'optional_label': 'Ixtiyoriy',
      'submit_review': 'Sharhni yuborish',
      'skip_for_now': 'Hozircha o\'tkazib yuborish',
      'rating_tag_on_time': 'Vaqtida',
      'rating_tag_friendly': 'Xushmuomala',
      'rating_tag_recommend': 'Tavsiya qilaman',
      'rating_submit_error': 'Baholashni yuborib bo\'lmadi. Qayta urinib ko\'ring.',
      // ==== Profil menyusi (qayta dizayn) ====
      'change_password_subtitle': 'Xavfsizlik parolingizni yangilang',
      'terms_subtitle': 'Foydalanish shartlari va maxfiylik siyosati',
      'avatar_preview_only_notice': 'Rasm faqat oldindan ko\'rsatilmoqda (hali serverga saqlanmaydi)',
      'avatar_upload_failed': 'Rasmni yuklashda xatolik yuz berdi',
      // ==== Fikr-mulohaza / FAQ ====
      'feedback': 'Fikr-mulohaza',
      'feedback_subtitle': 'Fikringizni bizga bildiring',
      'feedback_intro': 'Platformamizni yaxshilash uchun fikringizni bilishni istaymiz. Takliflaringiz to\'g\'ridan-to\'g\'ri jamoamizga yetib boradi.',
      'feedback_placeholder': 'Fikringizni shu yerga yozing...',
      'add_image': '+ Rasm qo\'shish',
      'send': 'Yuborish',
      'feedback_success': 'Rahmat! Fikringiz yuborildi',
      'faq': 'Ko\'p so\'raladigan savollar',
      'faq_subtitle': 'Javoblarni shu yerdan toping',
      // ==== Ovozli navigatsiya (TTS) ====
      'voice_turn_left': 'chapga buriling',
      'voice_turn_right': 'o\'ngga buriling',
      'voice_continue': 'to\'g\'riga yuring',
      'voice_distance_then_turn': '{dist} metrdan keyin, {direction}',
      'voice_go_straight': 'to\'g\'riga, {dist} harakatlaning',
      // ==== Yo'nalish faol emas (viloyat/tuman) ====
      'route_inactive_title': 'Bu yo\'nalish hozircha faol emas',
      'route_inactive_message': 'Tez orada faol bo\'ladi, xabardor qilamiz',
      'route_inactive_badge': 'Hozircha faol emas',
      // ==== Haydovchi liniyasi / rejalashtirilgan buyurtmalar ====
      'my_line': 'Mening yo\'nalishim',
      'scheduled_orders_title': 'Rejalashtirilgan buyurtmalar',
      'no_active_line': 'Hozircha liniya tanlanmagan',
      'active_line_label': 'Joriy liniyangiz',
      'cancel_line': 'Liniyani bekor qilish',
      'select_from_region': 'Qayerdan viloyatni tanlang',
      'select_to_region': 'Qayerga viloyatni tanlang',
      'line_duration': 'Davomiyligi',
      'hours_6': '6 soat',
      'hours_12': '12 soat',
      'hours_24': '24 soat',
      'confirm_line': 'Liniyani tasdiqlash',
      'today_tab': 'Bugun',
      'tomorrow_tab': 'Ertaga',
      'no_scheduled_orders': 'Hozircha rejalashtirilgan buyurtma yo\'q',
      'order_detail_title': 'Buyurtma tafsilotlari',
      'order_already_taken': 'Afsuski, bu buyurtmani boshqa haydovchi allaqachon qabul qildi',
      'set_new_line_title': 'Yangi liniya belgilash',
      'order_accepted_success': 'Buyurtma muvaffaqiyatli qabul qilindi',
      'scheduled_time_label': 'Vaqti',
      // ==== Buyurtma turi (Hozir/Bugun/Ertaga) ====
      'order_type_sheet_title': 'Buyurtma turini tanlang',
      'order_type_now': 'Hozir',
      'order_type_now_desc': 'Darhol haydovchi qidiriladi',
      'order_type_today': 'Bugun',
      'order_type_tomorrow': 'Ertaga',
      'order_type_select_time': 'Vaqtni tanlash',
      'order_type_min_time_error': 'Kamida 1 soat keyingi vaqtni tanlang',
      'order_type_pick_time_today': 'Bugun soat nechida?',
      'order_type_pick_time_tomorrow': 'Ertaga soat nechida?',
      // ==== Haydovchi yo'nalishi (qayta ishlangan) ====
      'no_route_yet': 'Sizning yo\'nalishingiz yo\'q',
      'add_route': 'Yo\'nalish qo\'shish',
      'create_new_route': 'Yangi yo\'nalish yaratish',
      'route_confirm_title': 'Siz ushbu yo\'nalishni tanladingiz',
      'route_confirm_desc': 'Endi sizga shu yo\'nalishdagi barcha rejalashtirilgan va real vaqtdagi buyurtmalarni qabul qilish imkoniyati beriladi',
      'understood': 'Tushunarli',
      'edit_route': 'Tahrirlash',
      'delete_route': 'O\'chirish',
      'route_deleted': 'Yo\'nalish o\'chirildi',
      'update_duration': 'Davomiylikni yangilash',
      'valid_until_label': 'Amal qilish muddati',
      'route_expired_title': 'Yo\'nalish muddati tugagan',
      'reactivate_route': 'Qayta faollashtirish',
      'active_until_label': 'Amal qilish muddati',
      'my_routes_label': 'Yo\'nalishlaringiz',
      'filter_by_route': 'Yo\'nalish bo\'yicha filtrlash',
      'all_routes': 'Barcha yo\'nalishlar',
      'your_route_badge': 'Sizning yo\'nalishingiz',
      'region_search_hint': 'Viloyat bo\'yicha qidirish...',
      'district_search_hint': 'Shahar yoki tuman bo\'yicha qidirish...',
      // ==== Tutorial bottom sheet'lar ====
      'tutorial_scheduled_title': 'Rejalashtirilgan buyurtmalar qanday ishlaydi?',
      'tutorial_scheduled_1': '"Bugun" va "Ertaga" bo\'limlaridan kerakli kunni tanlang',
      'tutorial_scheduled_2': 'Yo\'nalish bo\'yicha filtrlab, faqat sizga mos buyurtmalarni ko\'ring',
      'tutorial_scheduled_3': 'Buyurtma ustiga bosib tafsilotlarni ko\'ring va qabul qiling',
      'tutorial_scheduled_4': '"Sizning yo\'nalishingiz" belgisi — bu buyurtma sizning saqlangan yo\'nalishingizga mos kelishini bildiradi',
      'tutorial_routes_title': 'Yo\'nalishlaringiz nima uchun kerak?',
      'tutorial_routes_1': 'Doimiy yurgan yo\'nalishingizni saqlab qo\'ying (masalan Toshkent → Samarqand)',
      'tutorial_routes_2': 'Shu yo\'nalishga mos buyurtmalar sizga birinchi navbatda ko\'rsatiladi',
      'tutorial_routes_3': 'Yo\'nalish muddati tugasa, uni yangilashingiz kerak bo\'ladi',
      'tutorial_routes_4': '"+ Yangi yo\'nalish yaratish" tugmasi orqali istalgan vaqt qo\'shishingiz mumkin',
      'tutorial_create_route_title': 'Yo\'nalish qanday yaratiladi?',
      'tutorial_create_route_1': 'Avval "qayerdan" boshlanishini (viloyat, keyin tuman) tanlaysiz',
      'tutorial_create_route_2': 'Keyin "qayerga" borishini tanlaysiz',
      'tutorial_create_route_3': 'Yo\'nalish qancha vaqt faol bo\'lishini belgilaysiz (6/12/24 soat)',
      'tutorial_create_route_4': 'Tasdiqlagach, shu yo\'nalishga mos buyurtmalar sizga ustuvor ko\'rsatiladi',
      'tutorial_home_title': 'Asosiy ekran qanday ishlaydi?',
      'tutorial_home_1': 'Online/Offline tugmasini bosib, buyurtma qabul qilishni yoqing yoki o\'chiring',
      'tutorial_home_2': 'Yangi buyurtma kelganda, uni pastdan chapga suring — bu qabul qilish belgisi',
      'tutorial_home_3': 'Xaritani kattalashtirish, tekislash va 3D ko\'rinishga o\'tish tugmalari yon tomonda joylashgan',
      'tutorial_home_4': 'Aktiv buyurtma paytida, pastdagi panelni bosib to\'liq tafsilotlarni ko\'rishingiz mumkin',
      'tutorial_wallet_title': 'Hamyon qanday ishlaydi?',
      'tutorial_wallet_1': 'Har bir yakunlangan buyurtmadan komissiya avtomatik yechiladi',
      'tutorial_wallet_2': 'Balansingiz kamayib qolsa, "Balans to\'ldirish" tugmasi orqali to\'ldiring',
      'tutorial_wallet_3': 'Kartaga pul o\'tkazgach, chek rasmini yuklab, so\'rov yuboring',
      'tutorial_wallet_4': 'So\'rovingiz admin tomonidan 5-30 daqiqada tasdiqlanadi',
      'tutorial_feedback_title': 'Fikr-mulohaza qanday yuboriladi?',
      'tutorial_feedback_1': 'Taklif, shikoyat yoki muammongizni matn ko\'rinishida yozing',
      'tutorial_feedback_2': 'Agar kerak bo\'lsa, muammoni tasdiqlovchi rasm ilova qilishingiz mumkin',
      'tutorial_feedback_3': 'Xabaringiz to\'g\'ridan-to\'g\'ri administratsiyaga yetib boradi',
    },
    'ru': {
      'select_language': 'Выберите язык',
      'who_are_you': 'Кто вы?',
      'select_role': 'Выберите роль',
      'client': 'Грузоотправитель',
      'client_subtitle': 'Заказываю перевозку грузов',
      'driver': 'Водитель',
      'driver_subtitle': 'Перевожу грузы и зарабатываю',
      'phone_title': 'Ваш номер телефона',
      'phone_subtitle': 'Отправим код подтверждения по SMS',
      'send_code': 'Отправить код',
      'enter_code': 'Введите код',
      'code_sent': 'код отправлен на номер',
      'verify': 'Подтвердить',
      'resend': 'Отправить снова',
      'resend_in': 'Повторная отправка:',
      'skip': 'Пропустить',
      'next': 'Далее',
      'start': 'Начать',
      'home': 'Главная',
      'orders': 'Заказы',
      'wallet': 'Кошелёк',
      'profile': 'Профиль',
      'settings': 'Настройки',
      'notifications': 'Уведомления',
      'where_to': 'Куда отправить груз?',
      'saved_places': 'Сохранённые места',
      'tariffs': 'Тарифы',
      'full_name': 'Полное имя',
      'passport': 'Паспорт',
      'license': 'Водительское удостоверение',
      'tech_passport': 'Техпаспорт',
      'truck_type': 'Тип грузовика',
      'plate_number': 'Гос. номер',
      'capacity': 'Грузоподъёмность',
      'continue_btn': 'Продолжить',
      'pending_title': 'Данные приняты!',
      'pending_subtitle': 'Администратор рассмотрит и подтвердит.',
      'waiting': 'Ожидание...',
      'onboarding1_title': 'Перевозка проста!',
      'onboarding1_subtitle': 'Перевозите грузы из любого города в любой.',
      'onboarding2_title': 'Отслеживание в реальном времени',
      'onboarding2_subtitle': 'Следите за грузом на карте в реальном времени.',
      'onboarding3_title': 'Удобная оплата',
      'onboarding3_subtitle': 'Быстрая и безопасная оплата через кошелёк.',
      'step_sent': 'Документы отправлены',
      'step_reviewing': 'Администратор проверяет',
      'step_approved': 'Подтверждение',
      'pending_time': 'Ответ будет дан в течение 5-20 минут',
      'edit_profile': 'Редактировать профиль',
      'edit': 'Изменить',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'close': 'Закрыть',
      'confirm': 'Подтвердить',
      'apply': 'Применить',
      'name': 'Имя',
      'vehicle_info': 'Данные автомобиля',
      'vehicle_edit': 'Редактировать данные авто',
      'vehicle_edit_warning': 'Требуется подтверждение администратора',
      'verification_info': 'Данные верификации',
      'admin_approval_required': 'Требуется подтверждение администратора',
      'admin_approval_sent': 'Запрос отправлен! Ожидайте подтверждения.',
      'admin_approval_notice': 'Вы изменили данные верификации. В целях безопасности ожидайте подтверждения администратора.',
      'change_plate': 'Изменить гос. номер',
      'change_plate_subtitle': 'Требуется новый номер и техпаспорт',
      'new_plate': 'Новый гос. номер',
      'upload_tech_passport': 'Загрузите техпаспорт',
      'request_sent': 'Запрос отправлен',
      'request_pending': 'Администратор проверяет',
      'change_truck': 'Изменить тип грузовика',
      'documents': 'Документы',
      'uploaded': 'Загружено',
      'not_uploaded': 'Не загружено',
      'tap_to_upload': 'Нажмите для загрузки',
      'tap_to_change': 'Нажмите для изменения',
      'language': 'Язык',
      'theme': 'Тема',
      'select_theme': 'Выберите тему',
      'theme_auto': 'Авто',
      'theme_light': 'Светлая',
      'theme_dark': 'Тёмная',
      'logout': 'Выйти',
      'terms': 'Условия оферты',
      'personal_info': 'Личные данные',
      'app_settings': 'Настройки приложения',
      'app_tagline': 'Платформа грузоперевозок',
      'change_password': 'Изменить пароль',
      'current_password': 'Текущий пароль',
      'new_password': 'Новый пароль',
      'confirm_password': 'Подтвердите пароль',
      'change_phone': 'Изменить номер телефона',
      'phone_number_label': 'Номер телефона',
      'current_phone_number': 'Текущий номер телефона',
      'connected_phone_title': 'Номер, привязанный к вашему аккаунту',
      'change_phone_button': 'Изменить номер телефона',
      'resend_code': 'Отправить код повторно',
      'new_phone_number': 'Новый номер телефона',
      'phone_already_registered_hint': '',
      'phone_change_otp_sent': 'Код отправлен на номер {phone}',
      'phone_changed_success': 'Номер телефона успешно изменён!',
      'enter_new_phone_hint': 'Введите новый номер',
      'forgot_password': 'Забыли пароль?',
      'password_changed': 'Пароль успешно изменён',
      'password_mismatch': 'Пароли не совпадают',
      'password_too_short': 'Пароль должен содержать минимум 6 символов',
      'otp_sent': 'OTP код отправлен',
      'enter_otp': 'Введите OTP код',
      'otp_invalid_error': 'Неверный или просроченный OTP код',
      'set_new_password': 'Установите новый пароль',
      'reset_password': 'Восстановить пароль',
      'reset_password_subtitle': 'Отправим код подтверждения на ваш номер телефона',
      'reset_password_phone_prompt': 'Введите номер телефона, отправим OTP',
      'phone_incomplete_error': 'Введите номер телефона полностью',
      'reset_password_otp_note': 'Важно: подтвердите отправленный OTP код, чтобы сохранить новый пароль.',
      'password_field_hint': 'Пароль',
      'enter_password_error': 'Введите пароль',
      'invalid_credentials': 'Неверный номер телефона или пароль',
      'no_account_question': 'Нет аккаунта?',
      'create_new_account': 'Создать новый аккаунт',
      'invalid_or_expired_code': 'Неверный или истёкший код. Попробуйте снова.',
      'set_new_password_subtitle': 'Установите новый пароль не менее 6 символов',
      // ==== Client Home ====
      'menu': 'Меню',
      'my_orders': 'Мои заказы',
      'enter_address': 'Введите адрес',
      'place_order': 'Оформить заказ',
      'cancel_selection': 'Отмена',
      'from_question': 'Откуда?',
      'to_question': 'Куда?',
      'select_vehicle': 'Выберите тип автомобиля',
      'select_vehicle_hint': 'Выберите тип автомобиля',
      'select_button': 'Выбрать',
      'vehicle_help_text': 'Выберите тип автомобиля, подходящий по объёму вашего груза',
      'select_truck_error': 'Пожалуйста, выберите тип автомобиля',
      'select_truck_first_warning': 'Сначала выберите тип автомобиля',
      'weight_tons': 'Вес груза (тонн)',
      'enter_weight_error': 'Введите вес',
      'select_weight_hint': 'Выберите вес',
      'weight_help_text': 'Выберите примерный вес груза в тоннах',
      'auto_calculated_hint': 'Расстояние рассчитывается автоматически',
      'cargo_type_hint': 'Введите тип груза (например: мебель, продукты)',
      'enter_cargo_type_error': 'Введите тип груза',
      'order_when_label': 'Когда?',
      'select_time_hint': 'Выберите время',
      'select_time_error': 'Выберите время',
      'estimated_price_label': 'Примерная цена',
      'note_optional': 'Комментарий (необязательно)',
      'generic_error': 'Произошла ошибка',
      'error_timeout': 'Сервер не отвечает. Повторите попытку через некоторое время.',
      'error_no_connection': 'Нет подключения к интернету. Проверьте соединение и повторите попытку.',
      'error_server': 'Ошибка сервера. Повторите попытку через некоторое время.',
      'no_internet_title': 'Нет подключения к интернету',
      'no_internet_subtitle': 'Пожалуйста, проверьте подключение к интернету и повторите попытку',
      'retry_connection': 'Повторить попытку',
      'searching_driver': 'Поиск водителя...',
      'cancel_search': 'Отмена',
      'driver_assigned': 'Водитель назначен',
      'driver_arriving': 'Водитель едет',
      'loading_cargo': 'Загрузка груза',
      'in_transit': 'Груз в пути',
      'delivered_msg': 'Доставлено! 🎉',
      'order_active': 'Заказ активен',
      'complete_order': 'Завершить',
      'select_btn': 'Выбрать',
      'route_time_min': 'мин',
      'route_time_hour': 'ч',
      'current_location_label': 'Текущий адрес',
      'order_details': 'Детали',
      'vehicle_type_label': 'Тип автомобиля',
      'weight_label': 'Вес груза',
      'price_label': 'Примерная цена',
      'price_not_set': 'Пока не определена',
      'note_label': 'Комментарий',
      'arriving_in': 'приедет через',
      'location_permission_denied': 'Доступ к геолокации не предоставлен — выберите адрес вручную',
      // ==== Client Home: отдельные экраны (адрес/заказ/активный заказ) ====
      'select_address_title': 'Выбор адреса',
      'no_results_found': 'Результат не найден',
      'map_btn_label': 'Карта',
      'confirm_address_btn': 'Подтвердить адрес',
      'search_address_hint': 'Поиск адреса...',
      'selected_address_label': 'Выбранный адрес',
      'resolving_label': 'Определяется...',
      'address_not_found': 'Адрес не найден',
      'order_details_page_title': 'Детали заказа',
      'active_order_title': 'Активный заказ',
      'route_label': 'Маршрут',
      // ==== Страница активного заказа (редизайн) ====
      'live_label': 'LIVE',
      'route_summary_label': 'Сводка маршрута',
      'load_weight_label': 'Вес груза',
      'cargo_type_label': 'Тип груза',
      'arrived_at_label': 'Прибыл',
      'est_label': 'Ориентировочно',
      'estimated_arrival_label': 'Ориентировочное прибытие через {min} мин',
      'traffic_light': 'Свободно',
      'traffic_moderate': 'Умеренное движение',
      'traffic_heavy': 'Плотное движение',
      'turn_left_hint': 'Через {dist} поверните налево',
      'turn_right_hint': 'Через {dist} поверните направо',
      'turn_straight_hint': 'Через {dist} продолжайте прямо',
      'pickup_label': 'ЗАБОР',
      'dropoff_label': 'ДОСТАВКА',
      'emergency_support_label': 'Экстренная помощь',
      // ==== Меню (toggle) ====
      'active_order': 'Активный заказ',
      'active_order_subtitle': 'Отслеживайте текущий заказ',
      'my_orders_subtitle': 'Все ваши заказы',
      'notifications_subtitle': 'Новости и уведомления',
      'profile_subtitle': 'Личные данные',
      'language_subtitle': 'Выберите язык приложения',
      'theme_subtitle': 'Настройте внешний вид',
      'wallet_subtitle': 'Баланс и транзакции',
      'order_history_subtitle': 'Завершённые заказы',
      // ==== Сохранённые адреса ====
      'saved_places_subtitle': 'Часто используемые адреса',
      'no_saved_addresses': 'Пока нет сохранённых адресов',
      'add_new_address': 'Добавить новый адрес',
      'edit_address': 'Редактировать адрес',
      'add_address_title': 'Добавить адрес',
      'delete': 'Удалить',
      'delete_address_confirm_title': 'Удалить адрес',
      'delete_address_confirm_msg': 'Вы уверены, что хотите удалить этот адрес?',
      'address_name_optional_hint': 'Название (необязательно)',
      'address_field_hint': 'Найдите адрес или выберите на карте',
      'choose_on_map': 'Выбрать на карте',
      'address_saved_snackbar': 'Адрес сохранён',
      'address_updated_snackbar': 'Адрес обновлён',
      'address_deleted_snackbar': 'Адрес удалён',
      'quick_save_address_title': 'Сохранить адрес',
      // ==== Driver Home ====
      'online': 'Онлайн',
      'offline': 'Оффлайн',
      'order_waiting': 'Ожидание заказа',
      'you_are_online': 'Вы онлайн, ожидайте заказ',
      'you_are_offline': 'Вы оффлайн',
      'auto_offline_notice': 'Вы автоматически перешли в оффлайн (пропал GPS-сигнал). Чтобы продолжить, включите онлайн заново.',
      'gps_service_disabled_notice': 'Служба GPS отключена. Включите её в настройках телефона для определения местоположения.',
      'go_online_hint': 'Включите онлайн для получения заказов',
      'go_online': 'Включить онлайн',
      'new_order_label': 'НОВЫЙ ЗАКАЗ',
      'accept_order': 'Принять',
      'reject_order': 'Отклонить',
      'slide_to_accept': 'Проведите, чтобы принять',
      'going_to_client': 'Едет к клиенту',
      'cargo_on_way': 'Груз в пути',
      'picked_up_continue': 'Груз забран — в путь',
      'delivered_finish': 'Доставлено — завершить',
      // ==== Driver History ====
      'view_all_history': 'Смотреть все',
      'order_history_title': 'История заказов',
      'order_history_full_title': 'Все заказы',
      'filter_all': 'Все',
      'filter_active_only': 'Только активные',
      'filter_inactive_only': 'Только неактивные',
      'filter_delivered': 'Доставлено',
      'filter_cancelled': 'Отменено',
      'search_city_hint': 'Поиск по городу...',
      'no_orders_found': 'Заказы не найдены',
      'today': 'Сегодня',
      'yesterday': 'Вчера',
      'status_searching': 'Поиск водителя',
      'status_offered': 'Предложение отправлено',
      'status_accepted': 'Принято',
      'status_driver_arriving': 'Водитель едет',
      'status_loading': 'Загрузка',
      'status_in_transit': 'В пути',
      'status_delivered': 'Доставлено',
      'status_completed': 'Завершено',
      'status_cancelled': 'Отменено',
      // ==== Детали заказа (история, только просмотр) ====
      'status_history_label': 'История статуса',
      'sos_sent_label': 'Сигнал SOS отправлен',
      'additional_info_label': 'Дополнительная информация',
      'distance_traveled_label': 'Пройденное расстояние',
      'completion_duration_label': 'Время выполнения',
      'client_rating_label': 'Оценка клиента',
      // ==== История заказов (редизайн) ====
      'trip_label': 'Рейс',
      'from_label': 'Откуда',
      'to_label': 'Куда',
      'filter_pending': 'В ожидании',
      'month_01': 'Январь',
      'month_02': 'Февраль',
      'month_03': 'Март',
      'month_04': 'Апрель',
      'month_05': 'Май',
      'month_06': 'Июнь',
      'month_07': 'Июль',
      'month_08': 'Август',
      'month_09': 'Сентябрь',
      'month_10': 'Октябрь',
      'month_11': 'Ноябрь',
      'month_12': 'Декабрь',
      'month_short_01': 'янв',
      'month_short_02': 'фев',
      'month_short_03': 'мар',
      'month_short_04': 'апр',
      'month_short_05': 'май',
      'month_short_06': 'июн',
      'month_short_07': 'июл',
      'month_short_08': 'авг',
      'month_short_09': 'сен',
      'month_short_10': 'окт',
      'month_short_11': 'ноя',
      'month_short_12': 'дек',
      'other_date_label': 'Другое',
      // ==== Звонок / Отмена / Аватар ====
      'call': 'Позвонить',
      'call_confirm_title': 'Позвонить?',
      'call_confirm_message': 'Позвонить на этот номер?',
      'call_failed': 'Не удалось позвонить',
      'cancel_order_title': 'Отмена заказа',
      'cancel_order_message': 'Вы хотите отменить заказ? Это может повлиять на ваш рейтинг.',
      'yes_cancel_order': 'Да, отменить',
      'no_keep_order': 'Нет',
      'order_cancelled': 'Заказ отменён',
      'logout_confirm_title': 'Выход',
      'logout_confirm_message': 'Вы хотите выйти из системы?',
      'confirm_logout': 'Да, выйти',
      'profile_photo_optional': 'Фото профиля (необязательно)',
      'profile_photo_hint': 'Это необязательно — если не загрузите, будет использовано стандартное изображение',
      // ==== Кошелек (Wallet) ====
      'main_balance': 'Основной баланс',
      'total_trips': 'Всего рейсов',
      'total_earned': 'Общий доход',
      'topup_balance': 'Пополнить баланс',
      'topup_requests_history': 'История моих запросов на пополнение',
      'recent_transactions': 'Последние транзакции',
      'view_all': 'Смотреть все',
      'no_transactions': 'Транзакций нет',
      'card_number_copied': 'Номер карты скопирован!',
      'topup_card_label': 'Карта для перевода:',
      'copy_label': 'Копировать',
      'topup_card_hint': 'Скопируйте номер этой карты и оплатите через Click или Payme, затем загрузите чек.',
      'no_active_card': 'В данный момент нет активной карты для оплаты.',
      'topup_amount_label': 'Сумма оплаты (сум)',
      'topup_amount_note': 'Введите переведённую сумму полностью и правильно. Она должна совпадать с чеком.',
      'receipt_uploaded': 'Чек загружен ✓',
      'receipt_upload_prompt': 'Загрузите фото чека',
      'receipt_upload_hint': 'Выберите фото чека из галереи. Оно должно быть чётким и читаемым.',
      'topup_amount_error': 'Введите правильную сумму',
      'receipt_required_error': 'Загрузите фото чека',
      'topup_generic_error': 'Произошла ошибка. Попробуйте ещё раз.',
      'no_card_label': 'Карты нет',
      'submit_label': 'Отправить',
      'topup_request_sent': 'Запрос отправлен!',
      'topup_pending_note': 'Ожидайте подтверждения администратора.\nОбычно зачисляется на баланс в течение 5-30 минут.',
      'topup_history_title': 'История моих запросов',
      'topup_filter_all': 'Все',
      'topup_status_pending': 'В ожидании',
      'topup_status_approved': 'Одобрено',
      'topup_status_rejected': 'Отклонено',
      'topup_no_requests_found': 'Запросы не найдены',
      'topup_request_date': 'Дата запроса',
      'topup_approved_amount': 'Одобренная сумма',
      'topup_rejection_reason': 'Причина отклонения',
      'topup_receipt_label': 'Загруженный чек',
      'transaction_history_title': 'История транзакций',
      'search_placeholder': 'Поиск...',
      'no_transactions_found': 'Транзакции не найдены',
      // ==== Окно оценки (rating_dialog) ====
      'rating_dialog_title': 'Как прошла доставка?',
      'rating_dialog_subtitle': 'Ваш отзыв помогает нам поддерживать качество логистической сети GoWay',
      'review_placeholder': 'Напишите отзыв...',
      'optional_label': 'Необязательно',
      'submit_review': 'Отправить отзыв',
      'skip_for_now': 'Пропустить',
      'rating_tag_on_time': 'Вовремя',
      'rating_tag_friendly': 'Дружелюбный',
      'rating_tag_recommend': 'Рекомендую',
      'rating_submit_error': 'Не удалось отправить отзыв. Попробуйте снова.',
      // ==== Меню профиля (редизайн) ====
      'change_password_subtitle': 'Обновите пароль для безопасности',
      'terms_subtitle': 'Условия использования и конфиденциальность',
      'avatar_preview_only_notice': 'Изображение только для предпросмотра (пока не сохраняется на сервере)',
      'avatar_upload_failed': 'Не удалось загрузить изображение',
      // ==== Обратная связь / FAQ ====
      'feedback': 'Обратная связь',
      'feedback_subtitle': 'Поделитесь своим мнением',
      'feedback_intro': 'Мы хотим услышать ваше мнение об улучшении платформы. Ваши предложения напрямую попадают в нашу команду.',
      'feedback_placeholder': 'Напишите свой отзыв здесь...',
      'add_image': '+ Добавить фото',
      'send': 'Отправить',
      'feedback_success': 'Спасибо! Ваш отзыв отправлен',
      'faq': 'Часто задаваемые вопросы',
      'faq_subtitle': 'Найдите ответы здесь',
      // ==== Голосовая навигация (TTS) ====
      'voice_turn_left': 'поверните налево',
      'voice_turn_right': 'поверните направо',
      'voice_continue': 'продолжайте прямо',
      'voice_distance_then_turn': 'через {dist} метров, {direction}',
      'voice_go_straight': 'двигайтесь прямо {dist}',
      // ==== Направление не активно (регион/район) ====
      'route_inactive_title': 'Это направление пока не активно',
      'route_inactive_message': 'Скоро станет активным, мы вас уведомим',
      'route_inactive_badge': 'Пока не активно',
      // ==== Линия водителя / запланированные заказы ====
      'my_line': 'Мой маршрут',
      'scheduled_orders_title': 'Запланированные заказы',
      'no_active_line': 'Линия пока не выбрана',
      'active_line_label': 'Ваша текущая линия',
      'cancel_line': 'Отменить линию',
      'select_from_region': 'Выберите регион отправления',
      'select_to_region': 'Выберите регион назначения',
      'line_duration': 'Продолжительность',
      'hours_6': '6 часов',
      'hours_12': '12 часов',
      'hours_24': '24 часа',
      'confirm_line': 'Подтвердить линию',
      'today_tab': 'Сегодня',
      'tomorrow_tab': 'Завтра',
      'no_scheduled_orders': 'Пока нет запланированных заказов',
      'order_detail_title': 'Детали заказа',
      'order_already_taken': 'К сожалению, этот заказ уже принял другой водитель',
      'set_new_line_title': 'Указать новую линию',
      'order_accepted_success': 'Заказ успешно принят',
      'scheduled_time_label': 'Время',
      // ==== Тип заказа (Сейчас/Сегодня/Завтра) ====
      'order_type_sheet_title': 'Выберите тип заказа',
      'order_type_now': 'Сейчас',
      'order_type_now_desc': 'Водитель будет найден немедленно',
      'order_type_today': 'Сегодня',
      'order_type_tomorrow': 'Завтра',
      'order_type_select_time': 'Выбрать время',
      'order_type_min_time_error': 'Выберите время минимум через 1 час',
      'order_type_pick_time_today': 'Во сколько сегодня?',
      'order_type_pick_time_tomorrow': 'Во сколько завтра?',
      // ==== Маршрут водителя (переработано) ====
      'no_route_yet': 'У вас пока нет маршрута',
      'add_route': 'Добавить маршрут',
      'create_new_route': 'Создать новый маршрут',
      'route_confirm_title': 'Вы выбрали этот маршрут',
      'route_confirm_desc': 'Теперь вы можете принимать все запланированные и текущие заказы по этому маршруту',
      'understood': 'Понятно',
      'edit_route': 'Редактировать',
      'delete_route': 'Удалить',
      'route_deleted': 'Маршрут удалён',
      'update_duration': 'Обновить продолжительность',
      'valid_until_label': 'Действует до',
      'route_expired_title': 'Срок маршрута истёк',
      'reactivate_route': 'Активировать заново',
      'active_until_label': 'Действителен до',
      'my_routes_label': 'Ваши маршруты',
      'filter_by_route': 'Фильтр по маршруту',
      'all_routes': 'Все маршруты',
      'your_route_badge': 'Ваш маршрут',
      'region_search_hint': 'Поиск по региону...',
      'district_search_hint': 'Поиск по городу или району...',
      // ==== Обучающие bottom sheet'ы ====
      'tutorial_scheduled_title': 'Как работают запланированные заказы?',
      'tutorial_scheduled_1': 'Выберите нужный день во вкладках «Сегодня» и «Завтра»',
      'tutorial_scheduled_2': 'Отфильтруйте по маршруту, чтобы видеть только подходящие вам заказы',
      'tutorial_scheduled_3': 'Нажмите на заказ, чтобы посмотреть детали и принять его',
      'tutorial_scheduled_4': 'Метка «Ваш маршрут» означает, что заказ совпадает с вашим сохранённым маршрутом',
      'tutorial_routes_title': 'Зачем нужны ваши маршруты?',
      'tutorial_routes_1': 'Сохраните маршрут, по которому вы постоянно ездите (например, Ташкент → Самарканд)',
      'tutorial_routes_2': 'Заказы по этому маршруту будут показываться вам в первую очередь',
      'tutorial_routes_3': 'Когда срок действия маршрута истечёт, его нужно будет обновить',
      'tutorial_routes_4': 'Кнопка «+ Создать новый маршрут» позволяет добавить маршрут в любое время',
      'tutorial_create_route_title': 'Как создать маршрут?',
      'tutorial_create_route_1': 'Сначала выберите, откуда вы начинаете (область, затем район)',
      'tutorial_create_route_2': 'Затем выберите, куда вы едете',
      'tutorial_create_route_3': 'Укажите, сколько маршрут будет активен (6/12/24 часа)',
      'tutorial_create_route_4': 'После подтверждения заказы по этому маршруту будут показываться вам в приоритете',
      'tutorial_home_title': 'Как работает главный экран?',
      'tutorial_home_1': 'Нажмите кнопку Онлайн/Офлайн, чтобы включить или выключить приём заказов',
      'tutorial_home_2': 'Когда придёт новый заказ, проведите пальцем слева направо внизу — это означает принятие',
      'tutorial_home_3': 'Кнопки увеличения, выравнивания и 3D-вида карты находятся сбоку',
      'tutorial_home_4': 'Во время активного заказа нажмите на нижнюю панель, чтобы увидеть полную информацию',
      'tutorial_wallet_title': 'Как работает кошелёк?',
      'tutorial_wallet_1': 'С каждого завершённого заказа автоматически удерживается комиссия',
      'tutorial_wallet_2': 'Если баланс станет низким, пополните его через кнопку «Пополнить баланс»',
      'tutorial_wallet_3': 'После перевода на карту загрузите фото чека и отправьте запрос',
      'tutorial_wallet_4': 'Ваш запрос будет подтверждён администратором в течение 5-30 минут',
      'tutorial_feedback_title': 'Как отправить отзыв?',
      'tutorial_feedback_1': 'Опишите своё предложение, жалобу или проблему в виде текста',
      'tutorial_feedback_2': 'При необходимости вы можете прикрепить фото, подтверждающее проблему',
      'tutorial_feedback_3': 'Ваше сообщение будет напрямую направлено администрации',
    },
    'en': {
      'select_language': 'Choose language',
      'who_are_you': 'Who are you?',
      'select_role': 'Select your role',
      'client': 'Cargo Sender',
      'client_subtitle': 'I order cargo transportation',
      'driver': 'Driver',
      'driver_subtitle': 'I transport cargo and earn',
      'phone_title': 'Your phone number',
      'phone_subtitle': 'We will send a verification code via SMS',
      'send_code': 'Send code',
      'enter_code': 'Enter code',
      'code_sent': 'code sent to',
      'verify': 'Verify',
      'resend': 'Resend',
      'resend_in': 'Resend in:',
      'skip': 'Skip',
      'next': 'Next',
      'start': 'Get started',
      'home': 'Home',
      'orders': 'Orders',
      'wallet': 'Wallet',
      'profile': 'Profile',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'where_to': 'Where to send cargo?',
      'saved_places': 'Saved places',
      'tariffs': 'Tariffs',
      'full_name': 'Full name',
      'passport': 'Passport',
      'license': 'Driver\'s license',
      'tech_passport': 'Tech passport',
      'truck_type': 'Truck type',
      'plate_number': 'Plate number',
      'capacity': 'Load capacity',
      'continue_btn': 'Continue',
      'pending_title': 'Your data has been received!',
      'pending_subtitle': 'Admin will review and approve.',
      'waiting': 'Waiting...',
      'onboarding1_title': 'Easy cargo delivery!',
      'onboarding1_subtitle': 'Transport cargo from any city to any city.',
      'onboarding2_title': 'Real-time tracking',
      'onboarding2_subtitle': 'Track cargo on the map in real time.',
      'onboarding3_title': 'Easy payment',
      'onboarding3_subtitle': 'Fast and secure payment via wallet.',
      'step_sent': 'Documents submitted',
      'step_reviewing': 'Admin is reviewing',
      'step_approved': 'Approval',
      'pending_time': 'Response will be given within 5-20 minutes',
      'edit_profile': 'Edit profile',
      'edit': 'Edit',
      'save': 'Save',
      'cancel': 'Cancel',
      'close': 'Close',
      'confirm': 'Confirm',
      'apply': 'Apply',
      'name': 'Name',
      'vehicle_info': 'Vehicle info',
      'vehicle_edit': 'Edit vehicle info',
      'vehicle_edit_warning': 'Admin approval required',
      'verification_info': 'Verification info',
      'admin_approval_required': 'Admin approval required',
      'admin_approval_sent': 'Request sent! Waiting for admin approval.',
      'admin_approval_notice': 'You changed verification data. For security, please wait for admin approval.',
      'change_plate': 'Change plate number',
      'change_plate_subtitle': 'New plate and tech passport required',
      'new_plate': 'New plate number',
      'upload_tech_passport': 'Upload tech passport',
      'request_sent': 'Request sent',
      'request_pending': 'Admin is reviewing',
      'change_truck': 'Change truck type',
      'documents': 'Documents',
      'uploaded': 'Uploaded',
      'not_uploaded': 'Not uploaded',
      'tap_to_upload': 'Tap to upload',
      'tap_to_change': 'Tap to change',
      'language': 'Language',
      'theme': 'Theme',
      'select_theme': 'Choose theme',
      'theme_auto': 'Auto',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'logout': 'Logout',
      'terms': 'Terms of service',
      'personal_info': 'Personal info',
      'app_settings': 'App settings',
      'app_tagline': 'Cargo transportation platform',
      'change_password': 'Change password',
      'current_password': 'Current password',
      'new_password': 'New password',
      'confirm_password': 'Confirm password',
      'change_phone': 'Change phone number',
      'phone_number_label': 'Phone number',
      'current_phone_number': 'Current phone number',
      'connected_phone_title': 'Number linked to your account',
      'change_phone_button': 'Change phone number',
      'resend_code': 'Resend code',
      'new_phone_number': 'New phone number',
      'phone_already_registered_hint': '',
      'phone_change_otp_sent': 'Code sent to {phone}',
      'phone_changed_success': 'Phone number changed successfully!',
      'enter_new_phone_hint': 'Enter your new number',
      'forgot_password': 'Forgot password?',
      'password_changed': 'Password changed successfully',
      'password_mismatch': 'Passwords do not match',
      'password_too_short': 'Password must be at least 6 characters',
      'otp_sent': 'OTP code sent',
      'enter_otp': 'Enter OTP code',
      'otp_invalid_error': 'Invalid or expired OTP code',
      'set_new_password': 'Set new password',
      'reset_password': 'Reset password',
      'reset_password_subtitle': 'We will send a verification code to your phone number',
      'reset_password_phone_prompt': 'Enter your phone number, we will send an OTP',
      'phone_incomplete_error': 'Enter your full phone number',
      'reset_password_otp_note': 'Important: confirm the OTP code we sent to save your new password.',
      'password_field_hint': 'Password',
      'enter_password_error': 'Enter your password',
      'invalid_credentials': 'Invalid phone number or password',
      'no_account_question': 'Don\'t have an account?',
      'create_new_account': 'Create new account',
      'invalid_or_expired_code': 'Invalid or expired code. Please try again.',
      'set_new_password_subtitle': 'Set a new password with at least 6 characters',
      // ==== Client Home ====
      'menu': 'Menu',
      'my_orders': 'My orders',
      'enter_address': 'Enter address',
      'place_order': 'Place order',
      'cancel_selection': 'Cancel',
      'from_question': 'From?',
      'to_question': 'To?',
      'select_vehicle': 'Select vehicle type',
      'select_vehicle_hint': 'Select vehicle type',
      'select_button': 'Select',
      'vehicle_help_text': 'Choose a vehicle type that matches your cargo size',
      'select_truck_error': 'Please select a vehicle type',
      'select_truck_first_warning': 'First select a vehicle type',
      'weight_tons': 'Cargo weight (tons)',
      'enter_weight_error': 'Enter weight',
      'select_weight_hint': 'Select weight',
      'weight_help_text': 'Select the approximate weight of your cargo in tons',
      'auto_calculated_hint': 'Distance is calculated automatically',
      'cargo_type_hint': 'Enter cargo type (e.g. furniture, food)',
      'enter_cargo_type_error': 'Enter cargo type',
      'order_when_label': 'When?',
      'select_time_hint': 'Select time',
      'select_time_error': 'Select time',
      'estimated_price_label': 'Estimated price',
      'note_optional': 'Note (optional)',
      'generic_error': 'An error occurred',
      'error_timeout': 'The server did not respond. Please try again shortly.',
      'error_no_connection': 'No internet connection. Check your connection and try again.',
      'error_server': 'A server error occurred. Please try again shortly.',
      'no_internet_title': 'No internet connection',
      'no_internet_subtitle': 'Please check your internet connection and try again',
      'retry_connection': 'Retry',
      'searching_driver': 'Searching for driver...',
      'cancel_search': 'Cancel',
      'driver_assigned': 'Driver assigned',
      'driver_arriving': 'Driver is arriving',
      'loading_cargo': 'Loading cargo',
      'in_transit': 'Cargo in transit',
      'delivered_msg': 'Delivered! 🎉',
      'order_active': 'Order active',
      'complete_order': 'Complete',
      'select_btn': 'Select',
      'route_time_min': 'min',
      'route_time_hour': 'h',
      'current_location_label': 'Current location',
      'order_details': 'Details',
      'vehicle_type_label': 'Vehicle type',
      'weight_label': 'Cargo weight',
      'price_label': 'Estimated price',
      'price_not_set': 'Not set yet',
      'note_label': 'Note',
      'arriving_in': 'arriving in',
      'location_permission_denied': 'Location permission denied — please select address manually',
      // ==== Client Home: separate screens (address/order/active order) ====
      'select_address_title': 'Select address',
      'no_results_found': 'No results found',
      'map_btn_label': 'Map',
      'confirm_address_btn': 'Confirm address',
      'search_address_hint': 'Search address...',
      'selected_address_label': 'Selected address',
      'resolving_label': 'Resolving...',
      'address_not_found': 'Address not found',
      'order_details_page_title': 'Order details',
      'active_order_title': 'Active order',
      'route_label': 'Route',
      // ==== Active order page (redesign) ====
      'live_label': 'LIVE',
      'route_summary_label': 'Route Summary',
      'load_weight_label': 'Load Weight',
      'cargo_type_label': 'Cargo Type',
      'arrived_at_label': 'Arrived',
      'est_label': 'Est.',
      'estimated_arrival_label': 'Estimated arrival in {min} min',
      'traffic_light': 'Light traffic',
      'traffic_moderate': 'Moderate traffic',
      'traffic_heavy': 'Heavy traffic',
      'turn_left_hint': 'In {dist} turn left',
      'turn_right_hint': 'In {dist} turn right',
      'turn_straight_hint': 'In {dist} continue straight',
      'pickup_label': 'PICKUP',
      'dropoff_label': 'DROPOFF',
      'emergency_support_label': 'Emergency Support',
      // ==== Menu (toggle) sheet ====
      'active_order': 'Active order',
      'active_order_subtitle': 'Track your current order',
      'my_orders_subtitle': 'All your orders',
      'notifications_subtitle': 'Updates and alerts',
      'profile_subtitle': 'Personal details',
      'language_subtitle': 'Choose app language',
      'theme_subtitle': 'Customize appearance',
      'wallet_subtitle': 'Balance and transactions',
      'order_history_subtitle': 'Completed orders',
      // ==== Saved addresses ====
      'saved_places_subtitle': 'Frequently used addresses',
      'no_saved_addresses': 'No saved addresses yet',
      'add_new_address': 'Add new address',
      'edit_address': 'Edit address',
      'add_address_title': 'Add address',
      'delete': 'Delete',
      'delete_address_confirm_title': 'Delete address',
      'delete_address_confirm_msg': 'Are you sure you want to delete this address?',
      'address_name_optional_hint': 'Name (optional)',
      'address_field_hint': 'Search address or pick on map',
      'choose_on_map': 'Choose on map',
      'address_saved_snackbar': 'Address saved',
      'address_updated_snackbar': 'Address updated',
      'address_deleted_snackbar': 'Address deleted',
      'quick_save_address_title': 'Save address',
      // ==== Driver Home ====
      'online': 'Online',
      'offline': 'Offline',
      'order_waiting': 'Waiting for order',
      'you_are_online': 'You are online, wait for an order',
      'you_are_offline': 'You are offline',
      'auto_offline_notice': 'You went offline automatically (GPS signal lost). Go online again to continue.',
      'gps_service_disabled_notice': 'GPS service is disabled. Please enable it in your phone settings to detect your location.',
      'go_online_hint': 'Go online to receive orders',
      'go_online': 'Go online',
      'new_order_label': 'NEW ORDER',
      'accept_order': 'Accept',
      'reject_order': 'Reject',
      'slide_to_accept': 'Slide to accept',
      'going_to_client': 'Going to client',
      'cargo_on_way': 'Cargo on the way',
      'picked_up_continue': 'Picked up — go',
      'delivered_finish': 'Delivered — finish',
      // ==== Driver History ====
      'view_all_history': 'View all',
      'order_history_title': 'Order history',
      'order_history_full_title': 'All orders',
      'filter_all': 'All',
      'filter_active_only': 'Active only',
      'filter_inactive_only': 'Inactive only',
      'filter_delivered': 'Delivered',
      'filter_cancelled': 'Cancelled',
      'search_city_hint': 'Search by city...',
      'no_orders_found': 'No orders found',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'status_searching': 'Searching for driver',
      'status_offered': 'Offer sent',
      'status_accepted': 'Accepted',
      'status_driver_arriving': 'Driver arriving',
      'status_loading': 'Loading',
      'status_in_transit': 'In transit',
      'status_delivered': 'Delivered',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      // ==== Order detail (history, read-only) ====
      'status_history_label': 'Status history',
      'sos_sent_label': 'SOS signal sent',
      'additional_info_label': 'Additional information',
      'distance_traveled_label': 'Distance traveled',
      'completion_duration_label': 'Completion time',
      'client_rating_label': 'Client rating',
      // ==== Order history (redesign) ====
      'trip_label': 'Trip',
      'from_label': 'From',
      'to_label': 'To',
      'filter_pending': 'Pending',
      'month_01': 'January',
      'month_02': 'February',
      'month_03': 'March',
      'month_04': 'April',
      'month_05': 'May',
      'month_06': 'June',
      'month_07': 'July',
      'month_08': 'August',
      'month_09': 'September',
      'month_10': 'October',
      'month_11': 'November',
      'month_12': 'December',
      'month_short_01': 'Jan',
      'month_short_02': 'Feb',
      'month_short_03': 'Mar',
      'month_short_04': 'Apr',
      'month_short_05': 'May',
      'month_short_06': 'Jun',
      'month_short_07': 'Jul',
      'month_short_08': 'Aug',
      'month_short_09': 'Sep',
      'month_short_10': 'Oct',
      'month_short_11': 'Nov',
      'month_short_12': 'Dec',
      'other_date_label': 'Other',
      // ==== Call / Cancel order / Avatar ====
      'call': 'Call',
      'call_confirm_title': 'Do you want to call?',
      'call_confirm_message': 'Call this number?',
      'call_failed': 'Could not place the call',
      'cancel_order_title': 'Cancel order',
      'cancel_order_message': 'Do you want to cancel the order? This may affect your rating.',
      'yes_cancel_order': 'Yes, cancel',
      'no_keep_order': 'No',
      'order_cancelled': 'Order cancelled',
      'logout_confirm_title': 'Log out',
      'logout_confirm_message': 'Are you sure you want to log out?',
      'confirm_logout': 'Yes, log out',
      'profile_photo_optional': 'Profile photo (optional)',
      'profile_photo_hint': 'This is optional — if you don\'t upload one, a default image will be used',
      // ==== Wallet ====
      'main_balance': 'Main balance',
      'total_trips': 'Total trips',
      'total_earned': 'Total earned',
      'topup_balance': 'Top up balance',
      'topup_requests_history': 'My top-up request history',
      'recent_transactions': 'Recent transactions',
      'view_all': 'View all',
      'no_transactions': 'No transactions',
      'card_number_copied': 'Card number copied!',
      'topup_card_label': 'Card for transfer:',
      'copy_label': 'Copy',
      'topup_card_hint': 'Copy this card number, pay via Click or Payme, then upload the receipt.',
      'no_active_card': 'There is currently no active payment card.',
      'topup_amount_label': 'Payment amount (so\'m)',
      'topup_amount_note': 'Enter the amount you transferred fully and correctly. It should match the receipt.',
      'receipt_uploaded': 'Receipt uploaded ✓',
      'receipt_upload_prompt': 'Upload receipt photo',
      'receipt_upload_hint': 'Select the receipt photo from the gallery. Make sure it\'s clear and readable.',
      'topup_amount_error': 'Enter a valid amount',
      'receipt_required_error': 'Upload receipt photo',
      'topup_generic_error': 'An error occurred. Please try again.',
      'no_card_label': 'No card',
      'submit_label': 'Submit',
      'topup_request_sent': 'Request sent!',
      'topup_pending_note': 'Wait for admin confirmation.\nUsually credited to your balance within 5-30 minutes.',
      'topup_history_title': 'My request history',
      'topup_filter_all': 'All',
      'topup_status_pending': 'Pending',
      'topup_status_approved': 'Approved',
      'topup_status_rejected': 'Rejected',
      'topup_no_requests_found': 'No requests found',
      'topup_request_date': 'Request date',
      'topup_approved_amount': 'Approved amount',
      'topup_rejection_reason': 'Rejection reason',
      'topup_receipt_label': 'Uploaded receipt',
      'transaction_history_title': 'Transaction history',
      'search_placeholder': 'Search...',
      'no_transactions_found': 'No transactions found',
      // ==== Rating dialog ====
      'rating_dialog_title': 'How was your delivery?',
      'rating_dialog_subtitle': 'Your feedback helps us maintain the quality of the GoWay logistics network',
      'review_placeholder': 'Write a review...',
      'optional_label': 'Optional',
      'submit_review': 'Submit Review',
      'skip_for_now': 'Skip for now',
      'rating_tag_on_time': 'On time',
      'rating_tag_friendly': 'Friendly',
      'rating_tag_recommend': 'Would recommend',
      'rating_submit_error': 'Couldn\'t submit your review. Please try again.',
      // ==== Profile menu (redesign) ====
      'change_password_subtitle': 'Update your security password',
      'terms_subtitle': 'Terms of use and privacy policy',
      'avatar_preview_only_notice': 'Preview only — not yet saved to the server',
      'avatar_upload_failed': 'Failed to upload photo',
      // ==== Feedback / FAQ ====
      'feedback': 'Feedback',
      'feedback_subtitle': 'Share your thoughts with us',
      'feedback_intro': "We'd love to hear your thoughts on improving our platform. Your suggestions go straight to our team.",
      'feedback_placeholder': 'Write your feedback here...',
      'add_image': '+ Add photo',
      'send': 'Send',
      'feedback_success': 'Thank you! Your feedback has been sent',
      'faq': 'Frequently Asked Questions',
      'faq_subtitle': 'Find answers here',
      // ==== Voice navigation (TTS) ====
      'voice_turn_left': 'turn left',
      'voice_turn_right': 'turn right',
      'voice_continue': 'continue straight',
      'voice_distance_then_turn': 'in {dist} meters, {direction}',
      'voice_go_straight': 'continue straight for {dist}',
      // ==== Route not active (region/district) ====
      'route_inactive_title': 'This route is not active yet',
      'route_inactive_message': 'It will be active soon, we\'ll notify you',
      'route_inactive_badge': 'Not active yet',
      // ==== Driver line / scheduled orders ====
      'my_line': 'My route',
      'scheduled_orders_title': 'Scheduled orders',
      'no_active_line': 'No line selected yet',
      'active_line_label': 'Your current line',
      'cancel_line': 'Cancel line',
      'select_from_region': 'Select departure region',
      'select_to_region': 'Select destination region',
      'line_duration': 'Duration',
      'hours_6': '6 hours',
      'hours_12': '12 hours',
      'hours_24': '24 hours',
      'confirm_line': 'Confirm line',
      'today_tab': 'Today',
      'tomorrow_tab': 'Tomorrow',
      'no_scheduled_orders': 'No scheduled orders yet',
      'order_detail_title': 'Order details',
      'order_already_taken': 'Unfortunately, this order has already been accepted by another driver',
      'set_new_line_title': 'Set a new line',
      'order_accepted_success': 'Order accepted successfully',
      'scheduled_time_label': 'Time',
      // ==== Order type (Now/Today/Tomorrow) ====
      'order_type_sheet_title': 'Select order type',
      'order_type_now': 'Now',
      'order_type_now_desc': 'A driver will be found immediately',
      'order_type_today': 'Today',
      'order_type_tomorrow': 'Tomorrow',
      'order_type_select_time': 'Select time',
      'order_type_min_time_error': 'Please select a time at least 1 hour from now',
      'order_type_pick_time_today': 'What time today?',
      'order_type_pick_time_tomorrow': 'What time tomorrow?',
      // ==== Driver route (reworked) ====
      'no_route_yet': 'You don\'t have a route yet',
      'add_route': 'Add route',
      'create_new_route': 'Create new route',
      'route_confirm_title': 'You\'ve selected this route',
      'route_confirm_desc': 'You can now accept all scheduled and real-time orders on this route',
      'understood': 'Got it',
      'edit_route': 'Edit',
      'delete_route': 'Delete',
      'route_deleted': 'Route deleted',
      'update_duration': 'Update duration',
      'valid_until_label': 'Valid until',
      'route_expired_title': 'Your route has expired',
      'reactivate_route': 'Reactivate',
      'active_until_label': 'Active until',
      'my_routes_label': 'Your routes',
      'filter_by_route': 'Filter by route',
      'all_routes': 'All routes',
      'your_route_badge': 'Your route',
      'region_search_hint': 'Search by region...',
      'district_search_hint': 'Search by city or district...',
      // ==== Tutorial bottom sheets ====
      'tutorial_scheduled_title': 'How do scheduled orders work?',
      'tutorial_scheduled_1': 'Choose the day you need in the "Today" and "Tomorrow" tabs',
      'tutorial_scheduled_2': 'Filter by route to see only orders that match you',
      'tutorial_scheduled_3': 'Tap an order to see its details and accept it',
      'tutorial_scheduled_4': 'The "Your route" badge means the order matches your saved route',
      'tutorial_routes_title': 'Why do you need routes?',
      'tutorial_routes_1': 'Save the route you drive regularly (e.g. Tashkent → Samarkand)',
      'tutorial_routes_2': 'Orders on this route will be shown to you first',
      'tutorial_routes_3': "When a route expires, you'll need to renew it",
      'tutorial_routes_4': 'Use the "+ Create new route" button to add a route anytime',
      'tutorial_create_route_title': 'How to create a route?',
      'tutorial_create_route_1': "First choose where you start from (region, then district)",
      'tutorial_create_route_2': "Then choose where you're going",
      'tutorial_create_route_3': 'Set how long the route stays active (6/12/24 hours)',
      'tutorial_create_route_4': 'Once confirmed, orders on this route will be prioritized for you',
      'tutorial_home_title': 'How does the main screen work?',
      'tutorial_home_1': 'Tap the Online/Offline button to turn order acceptance on or off',
      'tutorial_home_2': 'When a new order arrives, slide from left to right at the bottom to accept it',
      'tutorial_home_3': 'Zoom, alignment, and 3D view buttons for the map are on the side',
      'tutorial_home_4': 'During an active order, tap the bottom panel to see full details',
      'tutorial_wallet_title': 'How does the wallet work?',
      'tutorial_wallet_1': 'Commission is automatically deducted from every completed order',
      'tutorial_wallet_2': 'If your balance runs low, top it up using the "Top up balance" button',
      'tutorial_wallet_3': 'After transferring money to the card, upload a receipt photo and send the request',
      'tutorial_wallet_4': 'Your request will be approved by the admin within 5-30 minutes',
      'tutorial_feedback_title': 'How to send feedback?',
      'tutorial_feedback_1': 'Write your suggestion, complaint, or issue as text',
      'tutorial_feedback_2': 'If needed, you can attach a photo confirming the issue',
      'tutorial_feedback_3': 'Your message goes directly to the administration',
    },
  };

  static String get(String key, String locale) {
    return _strings[locale]?[key] ?? _strings['uz']![key] ?? key;
  }
}