class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'uz': {
      'select_language': 'Tilni tanlang',
      'who_are_you': 'Siz kimsiz?',
      'select_role': 'Rolingizni tanlang',
      'client': 'Yuk beruvchi',
      'client_subtitle': 'Yuk tashish uchun buyurtma beraman',
      'driver': 'Haydovchi',
      'driver_subtitle': 'Yuk tashib daromad qilaman',
      'phone_title': 'Telefon raqamingiz',
      'phone_subtitle': 'SMS orqali tasdiqlash kodi yuboramiz',
      'send_code': 'Kodni yuborish',
      'enter_code': 'Kodni kiriting',
      'code_sent': 'raqamiga kod yuborildi',
      'verify': 'Tasdiqlash',
      'resend': 'Qayta yuborish',
      'resend_in': 'Qayta yuborish:',
      'skip': 'O\'tkazib yuborish',
      'next': 'Keyingi',
      'start': 'Boshlash',
      'home': 'Bosh',
      'orders': 'Buyurtmalar',
      'wallet': 'Hamyon',
      'profile': 'Profil',
      'settings': 'Sozlamalar',
      'notifications': 'Bildirishnomalar',
      'where_to': 'Qayerga yuk tashlaysiz?',
      'saved_places': 'Saqlangan manzillar',
      'tariffs': 'Tariflar',
      'full_name': 'To\'liq ism',
      'passport': 'Pasport',
      'license': 'Haydovchilik guvohnomasi',
      'tech_passport': 'Texnik pasport',
      'truck_type': 'Mashina turi',
      'plate_number': 'Davlat raqami',
      'capacity': 'Yuk ko\'tarish sig\'imi',
      'continue_btn': 'Davom etish',
      'pending_title': 'Ma\'lumotlaringiz qabul qilindi!',
      'pending_subtitle': 'Admin ko\'rib chiqib tasdiqlaydi. Bu biroz vaqt olishi mumkin.',
      'waiting': 'Kutilmoqda...',
      'onboarding1_title': 'Yuk tashish oson!',
      'onboarding1_subtitle': 'Istalgan shahardan istalgan shaharga yuk tashlang.',
      'onboarding2_title': 'Real vaqt kuzatuv',
      'onboarding2_subtitle': 'Yuk harakati xaritada real vaqtda kuzating.',
      'onboarding3_title': 'Qulay to\'lov',
      'onboarding3_subtitle': 'Hamyon orqali tez va xavfsiz to\'lov.',
      'step_sent': 'Hujjatlar yuborildi',
      'step_reviewing': 'Admin ko\'rib chiqmoqda',
      'step_approved': 'Tasdiqlash',
      'pending_time': 'Javob 5-20 daqiqa ichida beriladi',
      'edit_profile': 'Profilni tahrirlash',
      'edit': 'Tahrirlash',
      'save': 'Saqlash',
      'cancel': 'Bekor qilish',
      'close': 'Yopish',
      'confirm': 'Tasdiqlash',
      'name': 'Ism',
      'vehicle_info': 'Mashina ma\'lumotlari',
      'vehicle_edit': 'Mashina ma\'lumotlarini tahrirlash',
      'vehicle_edit_warning': 'Xavfsizlik uchun admin tasdiqlashi kerak',
      'verification_info': 'Tasdiqlanish ma\'lumotlari',
      'admin_approval_required': 'Admin tasdiqlashi talab etiladi',
      'admin_approval_sent': 'So\'rov yuborildi! Admin tasdiqlashini kuting.',
      'admin_approval_notice': 'Siz tasdiqlanish ma\'lumotlarini o\'zgartirdingiz. Xavfsizlik uchun admin tasdiqlashini kuting.',
      'change_plate': 'Davlat raqamini o\'zgartirish',
      'change_plate_subtitle': 'Yangi davlat raqami va texnik pasport talab qilinadi',
      'new_plate': 'Yangi davlat raqami',
      'upload_tech_passport': 'Texnik pasportni yuklang',
      'request_sent': 'So\'rov yuborildi',
      'request_pending': 'Admin ko\'rib chiqmoqda',
      'change_truck': 'Mashina turini o\'zgartirish',
      'documents': 'Hujjatlar',
      'uploaded': 'Yuklangan',
      'not_uploaded': 'Yuklanmagan',
      'tap_to_upload': 'Yuklash uchun bosing',
      'tap_to_change': 'O\'zgartirish uchun bosing',
      'language': 'Til',
      'theme': 'Tema',
      'select_theme': 'Temani tanlang',
      'theme_auto': 'Avto',
      'theme_light': 'Yorug\'',
      'theme_dark': 'Qorong\'u',
      'logout': 'Chiqish',
      'terms': 'Oferta shartlari',
      'personal_info': 'Shaxsiy ma\'lumotlar',
      'app_settings': 'Ilova sozlamalari',
      'change_password': 'Parolni o\'zgartirish',
      'current_password': 'Joriy parol',
      'new_password': 'Yangi parol',
      'confirm_password': 'Parolni tasdiqlang',
      'forgot_password': 'Parolni unutdingizmi?',
      'password_changed': 'Parol muvaffaqiyatli o\'zgartirildi',
      'password_mismatch': 'Parollar mos kelmaydi',
      'password_too_short': 'Parol kamida 6 ta belgidan iborat bo\'lishi kerak',
      'otp_sent': 'OTP kod yuborildi',
      'enter_otp': 'OTP kodni kiriting',
      'set_new_password': 'Yangi parol o\'rnating',
      'reset_password': 'Parolni tiklash',
      'reset_password_subtitle': 'Telefon raqamingizga tasdiqlash kodi yuboramiz',
      'password_field_hint': 'Parol',
      'enter_password_error': 'Parolni kiriting',
      'invalid_credentials': 'Telefon raqam yoki parol noto\'g\'ri',
      'no_account_question': 'Hisobingiz yo\'qmi?',
      'create_new_account': 'Yangi hisob yaratish',
      'invalid_or_expired_code': 'Kod noto\'g\'ri yoki eskirgan. Qaytadan urinib ko\'ring.',
      'set_new_password_subtitle': 'Kamida 6 ta belgidan iborat yangi parol o\'rnating',
      // ==== Client Home ====
      'menu': 'Menyu',
      'my_orders': 'Buyurtmalarim',
      'enter_address': 'Manzil kiriting',
      'place_order': 'Buyurtma berish',
      'cancel_selection': 'Bekor qilish',
      'from_question': 'Qayerdan?',
      'to_question': 'Qayerga?',
      'select_vehicle': 'Mashina turini tanlang',
      'select_truck_error': 'Iltimos, mashina turini tanlang',
      'weight_tons': 'Yuk og\'irligi (tonna)',
      'enter_weight_error': 'Og\'irlikni kiriting',
      'note_optional': 'Izoh (ixtiyoriy)',
      'generic_error': 'Xatolik yuz berdi',
      'error_timeout': 'Server javob bermadi. Birozdan so\'ng qayta urinib ko\'ring.',
      'error_no_connection': 'Internet aloqasi yo\'q. Aloqani tekshirib, qayta urinib ko\'ring.',
      'error_server': 'Serverda xatolik yuz berdi. Birozdan so\'ng qayta urinib ko\'ring.',
      'searching_driver': 'Haydovchi qidirilmoqda...',
      'cancel_search': 'Bekor qilish',
      'driver_assigned': 'Haydovchi tayinlandi',
      'driver_arriving': 'Haydovchi kelmoqda',
      'loading_cargo': 'Yuk yuklanmoqda',
      'in_transit': 'Yuk yo\'lda',
      'delivered_msg': 'Yetkazildi! 🎉',
      'order_active': 'Buyurtma faol',
      'complete_order': 'Yakunlash',
      'select_btn': 'Tanlang',
      'route_time_min': 'daqiqa',
      'route_time_hour': 'soat',
      'current_location_label': 'Joriy manzil',
      'order_details': 'Tafsilotlar',
      'vehicle_type_label': 'Mashina turi',
      'weight_label': 'Yuk og\'irligi',
      'price_label': 'Taxminiy narx',
      'price_not_set': 'Hali aniqlanmagan',
      'note_label': 'Izoh',
      'arriving_in': 'yetib keladi',
      'location_permission_denied': 'Joylashuv ruxsati berilmagan — manzilni qo\'lda tanlang',
      // ==== Client Home: alohida sahifalar (manzil/buyurtma/aktiv buyurtma) ====
      'select_address_title': 'Manzil tanlash',
      'no_results_found': 'Natija topilmadi',
      'map_btn_label': 'Xarita',
      'confirm_address_btn': 'Manzilni tasdiqlash',
      'search_address_hint': 'Manzil qidirish...',
      'selected_address_label': 'Tanlangan manzil',
      'resolving_label': 'Aniqlanmoqda...',
      'address_not_found': 'Manzil topilmadi',
      'order_details_page_title': 'Buyurtma tafsilotlari',
      'active_order_title': 'Faol buyurtma',
      'route_label': 'Marshrut',
      // ==== Faol buyurtma sahifasi (qayta dizayn) ====
      'live_label': 'LIVE',
      'route_summary_label': 'Marshrut xulosasi',
      'load_weight_label': 'Yuk og\'irligi',
      'cargo_type_label': 'Yuk turi',
      'arrived_at_label': 'Yetib keldi',
      'est_label': 'Taxminan',
      'estimated_arrival_label': 'Taxminiy yetib kelish: {min} daqiqada',
      'traffic_light': 'Yengil tirbandlik',
      'traffic_moderate': 'O\'rtacha tirbandlik',
      'traffic_heavy': 'Zich tirbandlik',
      'pickup_label': 'OLIB KETISH',
      'dropoff_label': 'YETKAZISH',
      'emergency_support_label': 'Favqulodda yordam',
      // ==== Menu (toggle) modali ====
      'active_order': 'Faol buyurtma',
      'active_order_subtitle': 'Joriy buyurtmangizni kuzating',
      'my_orders_subtitle': 'Barcha buyurtmalaringiz',
      'notifications_subtitle': 'Yangiliklar va bildirishnomalar',
      'profile_subtitle': 'Shaxsiy ma\'lumotlar',
      'language_subtitle': 'Ilova tilini tanlang',
      'theme_subtitle': 'Ko\'rinishni sozlang',
      'wallet_subtitle': 'Balans va tranzaksiyalar',
      'order_history_subtitle': 'Yakunlangan buyurtmalar',
      // ==== Saqlangan manzillar ====
      'saved_places_subtitle': 'Tez-tez ishlatiladigan manzillar',
      'no_saved_addresses': 'Hali saqlangan manzil yo\'q',
      'add_new_address': 'Yangi manzil qo\'shish',
      'edit_address': 'Manzilni tahrirlash',
      'add_address_title': 'Manzil qo\'shish',
      'delete': 'O\'chirish',
      'delete_address_confirm_title': 'Manzilni o\'chirish',
      'delete_address_confirm_msg': 'Bu manzilni o\'chirishni tasdiqlaysizmi?',
      'address_name_optional_hint': 'Nom (ixtiyoriy)',
      'address_field_hint': 'Manzil qidiring yoki xaritadan tanlang',
      'choose_on_map': 'Xaritadan tanlash',
      'address_saved_snackbar': 'Manzil saqlandi',
      'address_updated_snackbar': 'Manzil yangilandi',
      'address_deleted_snackbar': 'Manzil o\'chirildi',
      'quick_save_address_title': 'Manzilni saqlash',
      // ==== Driver Home ====
      'online': 'Online',
      'offline': 'Offline',
      'order_waiting': 'Buyurtma kutilmoqda',
      'you_are_online': 'Siz onlinesiz, buyurtma kelishini kuting',
      'you_are_offline': 'Siz offlainesiz',
      'go_online_hint': 'Buyurtma olish uchun onlayn bo\'ling',
      'go_online': 'Online bo\'lish',
      'new_order_label': 'YANGI BUYURTMA',
      'accept_order': 'Qabul qilish',
      'reject_order': 'Rad etish',
      'slide_to_accept': 'Qabul qilish uchun suring',
      'going_to_client': 'Mijozga bormoqda',
      'cargo_on_way': 'Yuk yo\'lda',
      'picked_up_continue': 'Yuk olindi — yo\'lga chiqish',
      'delivered_finish': 'Yetkazildi — yakunlash',
      // ==== Driver History ====
      'view_all_history': 'Barchasini ko\'rish',
      'order_history_title': 'Buyurtmalar tarixi',
      'order_history_full_title': 'Barcha buyurtmalar',
      'filter_all': 'Barchasi',
      'filter_delivered': 'Yetkazilgan',
      'filter_cancelled': 'Bekor qilingan',
      'search_city_hint': 'Shahar bo\'yicha qidirish...',
      'no_orders_found': 'Buyurtmalar topilmadi',
      'today': 'Bugun',
      'yesterday': 'Kecha',
      'status_searching': 'Haydovchi qidirilmoqda',
      'status_offered': 'Taklif yuborilgan',
      'status_accepted': 'Qabul qilindi',
      'status_driver_arriving': 'Haydovchi kelmoqda',
      'status_loading': 'Yuklanmoqda',
      'status_in_transit': 'Yo\'lda',
      'status_delivered': 'Yetkazildi',
      'status_completed': 'Yakunlandi',
      'status_cancelled': 'Bekor qilindi',
      // ==== Buyurtma tafsiloti (tarix, faqat o'qish) ====
      'status_history_label': 'Status tarixi',
      'sos_sent_label': 'SOS signal yuborilgan',
      'additional_info_label': 'Qo\'shimcha ma\'lumot',
      'distance_traveled_label': 'Bosib o\'tilgan masofa',
      'completion_duration_label': 'Yakunlanish vaqti',
      'client_rating_label': 'Mijoz bahosi',
      // ==== Buyurtmalar tarixi (qayta dizayn) ====
      'trip_label': 'Reys',
      'from_label': 'Qayerdan',
      'to_label': 'Qayerga',
      'filter_pending': 'Kutilmoqda',
      'month_01': 'Yanvar',
      'month_02': 'Fevral',
      'month_03': 'Mart',
      'month_04': 'Aprel',
      'month_05': 'May',
      'month_06': 'Iyun',
      'month_07': 'Iyul',
      'month_08': 'Avgust',
      'month_09': 'Sentabr',
      'month_10': 'Oktabr',
      'month_11': 'Noyabr',
      'month_12': 'Dekabr',
      // ==== Qo'ng'iroq / Bekor qilish / Avatar ====
      'call': 'Qo\'ng\'iroq qilish',
      'call_confirm_title': 'Qo\'ng\'iroq qilasizmi?',
      'call_confirm_message': 'Ushbu raqamga qo\'ng\'iroq qilinsinmi?',
      'call_failed': 'Qo\'ng\'iroq qilib bo\'lmadi',
      'cancel_order_title': 'Buyurtmani bekor qilish',
      'cancel_order_message': 'Buyurtmani bekor qilmoqchimisiz? Bu sizning reytingingizga ta\'sir qilishi mumkin.',
      'yes_cancel_order': 'Ha, bekor qilish',
      'no_keep_order': 'Yo\'q',
      'order_cancelled': 'Buyurtma bekor qilindi',
      'profile_photo_optional': 'Profil rasmi (ixtiyoriy)',
      'profile_photo_hint': 'Bu majburiy emas, agar yuklamasangiz standart rasm ishlatiladi',
      // ==== Baholash oynasi (rating_dialog) ====
      'rating_dialog_title': 'Yetkazib berish qanday bo\'ldi?',
      'rating_dialog_subtitle': 'Sizning fikringiz GoWay xizmat sifatini yaxshilashga yordam beradi',
      'review_placeholder': 'Sharh yozing...',
      'optional_label': 'Ixtiyoriy',
      'submit_review': 'Sharhni yuborish',
      'skip_for_now': 'Hozircha o\'tkazib yuborish',
      'rating_tag_on_time': 'Vaqtida',
      'rating_tag_friendly': 'Xushmuomala',
      'rating_tag_recommend': 'Tavsiya qilaman',
      'rating_submit_error': 'Baholashni yuborib bo\'lmadi. Qayta urinib ko\'ring.',
      // ==== Profil menyusi (qayta dizayn) ====
      'change_password_subtitle': 'Xavfsizlik parolingizni yangilang',
      'terms_subtitle': 'Foydalanish shartlari va maxfiylik siyosati',
      'avatar_preview_only_notice': 'Rasm faqat oldindan ko\'rsatilmoqda (hali serverga saqlanmaydi)',
      'avatar_upload_failed': 'Rasmni yuklashda xatolik yuz berdi',
    },
    'ru': {
      'select_language': 'Выберите язык',
      'who_are_you': 'Кто вы?',
      'select_role': 'Выберите роль',
      'client': 'Грузоотправитель',
      'client_subtitle': 'Заказываю перевозку грузов',
      'driver': 'Водитель',
      'driver_subtitle': 'Перевожу грузы и зарабатываю',
      'phone_title': 'Ваш номер телефона',
      'phone_subtitle': 'Отправим код подтверждения по SMS',
      'send_code': 'Отправить код',
      'enter_code': 'Введите код',
      'code_sent': 'код отправлен на номер',
      'verify': 'Подтвердить',
      'resend': 'Отправить снова',
      'resend_in': 'Повторная отправка:',
      'skip': 'Пропустить',
      'next': 'Далее',
      'start': 'Начать',
      'home': 'Главная',
      'orders': 'Заказы',
      'wallet': 'Кошелёк',
      'profile': 'Профиль',
      'settings': 'Настройки',
      'notifications': 'Уведомления',
      'where_to': 'Куда отправить груз?',
      'saved_places': 'Сохранённые места',
      'tariffs': 'Тарифы',
      'full_name': 'Полное имя',
      'passport': 'Паспорт',
      'license': 'Водительское удостоверение',
      'tech_passport': 'Техпаспорт',
      'truck_type': 'Тип грузовика',
      'plate_number': 'Гос. номер',
      'capacity': 'Грузоподъёмность',
      'continue_btn': 'Продолжить',
      'pending_title': 'Данные приняты!',
      'pending_subtitle': 'Администратор рассмотрит и подтвердит.',
      'waiting': 'Ожидание...',
      'onboarding1_title': 'Перевозка проста!',
      'onboarding1_subtitle': 'Перевозите грузы из любого города в любой.',
      'onboarding2_title': 'Отслеживание в реальном времени',
      'onboarding2_subtitle': 'Следите за грузом на карте в реальном времени.',
      'onboarding3_title': 'Удобная оплата',
      'onboarding3_subtitle': 'Быстрая и безопасная оплата через кошелёк.',
      'step_sent': 'Документы отправлены',
      'step_reviewing': 'Администратор проверяет',
      'step_approved': 'Подтверждение',
      'pending_time': 'Ответ будет дан в течение 5-20 минут',
      'edit_profile': 'Редактировать профиль',
      'edit': 'Изменить',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'close': 'Закрыть',
      'confirm': 'Подтвердить',
      'name': 'Имя',
      'vehicle_info': 'Данные автомобиля',
      'vehicle_edit': 'Редактировать данные авто',
      'vehicle_edit_warning': 'Требуется подтверждение администратора',
      'verification_info': 'Данные верификации',
      'admin_approval_required': 'Требуется подтверждение администратора',
      'admin_approval_sent': 'Запрос отправлен! Ожидайте подтверждения.',
      'admin_approval_notice': 'Вы изменили данные верификации. В целях безопасности ожидайте подтверждения администратора.',
      'change_plate': 'Изменить гос. номер',
      'change_plate_subtitle': 'Требуется новый номер и техпаспорт',
      'new_plate': 'Новый гос. номер',
      'upload_tech_passport': 'Загрузите техпаспорт',
      'request_sent': 'Запрос отправлен',
      'request_pending': 'Администратор проверяет',
      'change_truck': 'Изменить тип грузовика',
      'documents': 'Документы',
      'uploaded': 'Загружено',
      'not_uploaded': 'Не загружено',
      'tap_to_upload': 'Нажмите для загрузки',
      'tap_to_change': 'Нажмите для изменения',
      'language': 'Язык',
      'theme': 'Тема',
      'select_theme': 'Выберите тему',
      'theme_auto': 'Авто',
      'theme_light': 'Светлая',
      'theme_dark': 'Тёмная',
      'logout': 'Выйти',
      'terms': 'Условия оферты',
      'personal_info': 'Личные данные',
      'app_settings': 'Настройки приложения',
      'change_password': 'Изменить пароль',
      'current_password': 'Текущий пароль',
      'new_password': 'Новый пароль',
      'confirm_password': 'Подтвердите пароль',
      'forgot_password': 'Забыли пароль?',
      'password_changed': 'Пароль успешно изменён',
      'password_mismatch': 'Пароли не совпадают',
      'password_too_short': 'Пароль должен содержать минимум 6 символов',
      'otp_sent': 'OTP код отправлен',
      'enter_otp': 'Введите OTP код',
      'set_new_password': 'Установите новый пароль',
      'reset_password': 'Восстановить пароль',
      'reset_password_subtitle': 'Отправим код подтверждения на ваш номер телефона',
      'password_field_hint': 'Пароль',
      'enter_password_error': 'Введите пароль',
      'invalid_credentials': 'Неверный номер телефона или пароль',
      'no_account_question': 'Нет аккаунта?',
      'create_new_account': 'Создать новый аккаунт',
      'invalid_or_expired_code': 'Неверный или истёкший код. Попробуйте снова.',
      'set_new_password_subtitle': 'Установите новый пароль не менее 6 символов',
      // ==== Client Home ====
      'menu': 'Меню',
      'my_orders': 'Мои заказы',
      'enter_address': 'Введите адрес',
      'place_order': 'Оформить заказ',
      'cancel_selection': 'Отмена',
      'from_question': 'Откуда?',
      'to_question': 'Куда?',
      'select_vehicle': 'Выберите тип автомобиля',
      'select_truck_error': 'Пожалуйста, выберите тип автомобиля',
      'weight_tons': 'Вес груза (тонн)',
      'enter_weight_error': 'Введите вес',
      'note_optional': 'Комментарий (необязательно)',
      'generic_error': 'Произошла ошибка',
      'error_timeout': 'Сервер не отвечает. Повторите попытку через некоторое время.',
      'error_no_connection': 'Нет подключения к интернету. Проверьте соединение и повторите попытку.',
      'error_server': 'Ошибка сервера. Повторите попытку через некоторое время.',
      'searching_driver': 'Поиск водителя...',
      'cancel_search': 'Отмена',
      'driver_assigned': 'Водитель назначен',
      'driver_arriving': 'Водитель едет',
      'loading_cargo': 'Загрузка груза',
      'in_transit': 'Груз в пути',
      'delivered_msg': 'Доставлено! 🎉',
      'order_active': 'Заказ активен',
      'complete_order': 'Завершить',
      'select_btn': 'Выбрать',
      'route_time_min': 'мин',
      'route_time_hour': 'ч',
      'current_location_label': 'Текущий адрес',
      'order_details': 'Детали',
      'vehicle_type_label': 'Тип автомобиля',
      'weight_label': 'Вес груза',
      'price_label': 'Примерная цена',
      'price_not_set': 'Пока не определена',
      'note_label': 'Комментарий',
      'arriving_in': 'приедет через',
      'location_permission_denied': 'Доступ к геолокации не предоставлен — выберите адрес вручную',
      // ==== Client Home: отдельные экраны (адрес/заказ/активный заказ) ====
      'select_address_title': 'Выбор адреса',
      'no_results_found': 'Результат не найден',
      'map_btn_label': 'Карта',
      'confirm_address_btn': 'Подтвердить адрес',
      'search_address_hint': 'Поиск адреса...',
      'selected_address_label': 'Выбранный адрес',
      'resolving_label': 'Определяется...',
      'address_not_found': 'Адрес не найден',
      'order_details_page_title': 'Детали заказа',
      'active_order_title': 'Активный заказ',
      'route_label': 'Маршрут',
      // ==== Страница активного заказа (редизайн) ====
      'live_label': 'LIVE',
      'route_summary_label': 'Сводка маршрута',
      'load_weight_label': 'Вес груза',
      'cargo_type_label': 'Тип груза',
      'arrived_at_label': 'Прибыл',
      'est_label': 'Ориентировочно',
      'estimated_arrival_label': 'Ориентировочное прибытие через {min} мин',
      'traffic_light': 'Свободно',
      'traffic_moderate': 'Умеренное движение',
      'traffic_heavy': 'Плотное движение',
      'pickup_label': 'ЗАБОР',
      'dropoff_label': 'ДОСТАВКА',
      'emergency_support_label': 'Экстренная помощь',
      // ==== Меню (toggle) ====
      'active_order': 'Активный заказ',
      'active_order_subtitle': 'Отслеживайте текущий заказ',
      'my_orders_subtitle': 'Все ваши заказы',
      'notifications_subtitle': 'Новости и уведомления',
      'profile_subtitle': 'Личные данные',
      'language_subtitle': 'Выберите язык приложения',
      'theme_subtitle': 'Настройте внешний вид',
      'wallet_subtitle': 'Баланс и транзакции',
      'order_history_subtitle': 'Завершённые заказы',
      // ==== Сохранённые адреса ====
      'saved_places_subtitle': 'Часто используемые адреса',
      'no_saved_addresses': 'Пока нет сохранённых адресов',
      'add_new_address': 'Добавить новый адрес',
      'edit_address': 'Редактировать адрес',
      'add_address_title': 'Добавить адрес',
      'delete': 'Удалить',
      'delete_address_confirm_title': 'Удалить адрес',
      'delete_address_confirm_msg': 'Вы уверены, что хотите удалить этот адрес?',
      'address_name_optional_hint': 'Название (необязательно)',
      'address_field_hint': 'Найдите адрес или выберите на карте',
      'choose_on_map': 'Выбрать на карте',
      'address_saved_snackbar': 'Адрес сохранён',
      'address_updated_snackbar': 'Адрес обновлён',
      'address_deleted_snackbar': 'Адрес удалён',
      'quick_save_address_title': 'Сохранить адрес',
      // ==== Driver Home ====
      'online': 'Онлайн',
      'offline': 'Оффлайн',
      'order_waiting': 'Ожидание заказа',
      'you_are_online': 'Вы онлайн, ожидайте заказ',
      'you_are_offline': 'Вы оффлайн',
      'go_online_hint': 'Включите онлайн для получения заказов',
      'go_online': 'Включить онлайн',
      'new_order_label': 'НОВЫЙ ЗАКАЗ',
      'accept_order': 'Принять',
      'reject_order': 'Отклонить',
      'slide_to_accept': 'Проведите, чтобы принять',
      'going_to_client': 'Едет к клиенту',
      'cargo_on_way': 'Груз в пути',
      'picked_up_continue': 'Груз забран — в путь',
      'delivered_finish': 'Доставлено — завершить',
      // ==== Driver History ====
      'view_all_history': 'Смотреть все',
      'order_history_title': 'История заказов',
      'order_history_full_title': 'Все заказы',
      'filter_all': 'Все',
      'filter_delivered': 'Доставлено',
      'filter_cancelled': 'Отменено',
      'search_city_hint': 'Поиск по городу...',
      'no_orders_found': 'Заказы не найдены',
      'today': 'Сегодня',
      'yesterday': 'Вчера',
      'status_searching': 'Поиск водителя',
      'status_offered': 'Предложение отправлено',
      'status_accepted': 'Принято',
      'status_driver_arriving': 'Водитель едет',
      'status_loading': 'Загрузка',
      'status_in_transit': 'В пути',
      'status_delivered': 'Доставлено',
      'status_completed': 'Завершено',
      'status_cancelled': 'Отменено',
      // ==== Детали заказа (история, только просмотр) ====
      'status_history_label': 'История статуса',
      'sos_sent_label': 'Сигнал SOS отправлен',
      'additional_info_label': 'Дополнительная информация',
      'distance_traveled_label': 'Пройденное расстояние',
      'completion_duration_label': 'Время выполнения',
      'client_rating_label': 'Оценка клиента',
      // ==== История заказов (редизайн) ====
      'trip_label': 'Рейс',
      'from_label': 'Откуда',
      'to_label': 'Куда',
      'filter_pending': 'В ожидании',
      'month_01': 'Январь',
      'month_02': 'Февраль',
      'month_03': 'Март',
      'month_04': 'Апрель',
      'month_05': 'Май',
      'month_06': 'Июнь',
      'month_07': 'Июль',
      'month_08': 'Август',
      'month_09': 'Сентябрь',
      'month_10': 'Октябрь',
      'month_11': 'Ноябрь',
      'month_12': 'Декабрь',
      // ==== Звонок / Отмена / Аватар ====
      'call': 'Позвонить',
      'call_confirm_title': 'Позвонить?',
      'call_confirm_message': 'Позвонить на этот номер?',
      'call_failed': 'Не удалось позвонить',
      'cancel_order_title': 'Отмена заказа',
      'cancel_order_message': 'Вы хотите отменить заказ? Это может повлиять на ваш рейтинг.',
      'yes_cancel_order': 'Да, отменить',
      'no_keep_order': 'Нет',
      'order_cancelled': 'Заказ отменён',
      'profile_photo_optional': 'Фото профиля (необязательно)',
      'profile_photo_hint': 'Это необязательно — если не загрузите, будет использовано стандартное изображение',
      // ==== Окно оценки (rating_dialog) ====
      'rating_dialog_title': 'Как прошла доставка?',
      'rating_dialog_subtitle': 'Ваш отзыв помогает нам поддерживать качество логистической сети GoWay',
      'review_placeholder': 'Напишите отзыв...',
      'optional_label': 'Необязательно',
      'submit_review': 'Отправить отзыв',
      'skip_for_now': 'Пропустить',
      'rating_tag_on_time': 'Вовремя',
      'rating_tag_friendly': 'Дружелюбный',
      'rating_tag_recommend': 'Рекомендую',
      'rating_submit_error': 'Не удалось отправить отзыв. Попробуйте снова.',
      // ==== Меню профиля (редизайн) ====
      'change_password_subtitle': 'Обновите пароль для безопасности',
      'terms_subtitle': 'Условия использования и конфиденциальность',
      'avatar_preview_only_notice': 'Изображение только для предпросмотра (пока не сохраняется на сервере)',
      'avatar_upload_failed': 'Не удалось загрузить изображение',
    },
    'en': {
      'select_language': 'Choose language',
      'who_are_you': 'Who are you?',
      'select_role': 'Select your role',
      'client': 'Cargo Sender',
      'client_subtitle': 'I order cargo transportation',
      'driver': 'Driver',
      'driver_subtitle': 'I transport cargo and earn',
      'phone_title': 'Your phone number',
      'phone_subtitle': 'We will send a verification code via SMS',
      'send_code': 'Send code',
      'enter_code': 'Enter code',
      'code_sent': 'code sent to',
      'verify': 'Verify',
      'resend': 'Resend',
      'resend_in': 'Resend in:',
      'skip': 'Skip',
      'next': 'Next',
      'start': 'Get started',
      'home': 'Home',
      'orders': 'Orders',
      'wallet': 'Wallet',
      'profile': 'Profile',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'where_to': 'Where to send cargo?',
      'saved_places': 'Saved places',
      'tariffs': 'Tariffs',
      'full_name': 'Full name',
      'passport': 'Passport',
      'license': 'Driver\'s license',
      'tech_passport': 'Tech passport',
      'truck_type': 'Truck type',
      'plate_number': 'Plate number',
      'capacity': 'Load capacity',
      'continue_btn': 'Continue',
      'pending_title': 'Your data has been received!',
      'pending_subtitle': 'Admin will review and approve.',
      'waiting': 'Waiting...',
      'onboarding1_title': 'Easy cargo delivery!',
      'onboarding1_subtitle': 'Transport cargo from any city to any city.',
      'onboarding2_title': 'Real-time tracking',
      'onboarding2_subtitle': 'Track cargo on the map in real time.',
      'onboarding3_title': 'Easy payment',
      'onboarding3_subtitle': 'Fast and secure payment via wallet.',
      'step_sent': 'Documents submitted',
      'step_reviewing': 'Admin is reviewing',
      'step_approved': 'Approval',
      'pending_time': 'Response will be given within 5-20 minutes',
      'edit_profile': 'Edit profile',
      'edit': 'Edit',
      'save': 'Save',
      'cancel': 'Cancel',
      'close': 'Close',
      'confirm': 'Confirm',
      'name': 'Name',
      'vehicle_info': 'Vehicle info',
      'vehicle_edit': 'Edit vehicle info',
      'vehicle_edit_warning': 'Admin approval required',
      'verification_info': 'Verification info',
      'admin_approval_required': 'Admin approval required',
      'admin_approval_sent': 'Request sent! Waiting for admin approval.',
      'admin_approval_notice': 'You changed verification data. For security, please wait for admin approval.',
      'change_plate': 'Change plate number',
      'change_plate_subtitle': 'New plate and tech passport required',
      'new_plate': 'New plate number',
      'upload_tech_passport': 'Upload tech passport',
      'request_sent': 'Request sent',
      'request_pending': 'Admin is reviewing',
      'change_truck': 'Change truck type',
      'documents': 'Documents',
      'uploaded': 'Uploaded',
      'not_uploaded': 'Not uploaded',
      'tap_to_upload': 'Tap to upload',
      'tap_to_change': 'Tap to change',
      'language': 'Language',
      'theme': 'Theme',
      'select_theme': 'Choose theme',
      'theme_auto': 'Auto',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'logout': 'Logout',
      'terms': 'Terms of service',
      'personal_info': 'Personal info',
      'app_settings': 'App settings',
      'change_password': 'Change password',
      'current_password': 'Current password',
      'new_password': 'New password',
      'confirm_password': 'Confirm password',
      'forgot_password': 'Forgot password?',
      'password_changed': 'Password changed successfully',
      'password_mismatch': 'Passwords do not match',
      'password_too_short': 'Password must be at least 6 characters',
      'otp_sent': 'OTP code sent',
      'enter_otp': 'Enter OTP code',
      'set_new_password': 'Set new password',
      'reset_password': 'Reset password',
      'reset_password_subtitle': 'We will send a verification code to your phone number',
      'password_field_hint': 'Password',
      'enter_password_error': 'Enter your password',
      'invalid_credentials': 'Invalid phone number or password',
      'no_account_question': 'Don\'t have an account?',
      'create_new_account': 'Create new account',
      'invalid_or_expired_code': 'Invalid or expired code. Please try again.',
      'set_new_password_subtitle': 'Set a new password with at least 6 characters',
      // ==== Client Home ====
      'menu': 'Menu',
      'my_orders': 'My orders',
      'enter_address': 'Enter address',
      'place_order': 'Place order',
      'cancel_selection': 'Cancel',
      'from_question': 'From?',
      'to_question': 'To?',
      'select_vehicle': 'Select vehicle type',
      'select_truck_error': 'Please select a vehicle type',
      'weight_tons': 'Cargo weight (tons)',
      'enter_weight_error': 'Enter weight',
      'note_optional': 'Note (optional)',
      'generic_error': 'An error occurred',
      'error_timeout': 'The server did not respond. Please try again shortly.',
      'error_no_connection': 'No internet connection. Check your connection and try again.',
      'error_server': 'A server error occurred. Please try again shortly.',
      'searching_driver': 'Searching for driver...',
      'cancel_search': 'Cancel',
      'driver_assigned': 'Driver assigned',
      'driver_arriving': 'Driver is arriving',
      'loading_cargo': 'Loading cargo',
      'in_transit': 'Cargo in transit',
      'delivered_msg': 'Delivered! 🎉',
      'order_active': 'Order active',
      'complete_order': 'Complete',
      'select_btn': 'Select',
      'route_time_min': 'min',
      'route_time_hour': 'h',
      'current_location_label': 'Current location',
      'order_details': 'Details',
      'vehicle_type_label': 'Vehicle type',
      'weight_label': 'Cargo weight',
      'price_label': 'Estimated price',
      'price_not_set': 'Not set yet',
      'note_label': 'Note',
      'arriving_in': 'arriving in',
      'location_permission_denied': 'Location permission denied — please select address manually',
      // ==== Client Home: separate screens (address/order/active order) ====
      'select_address_title': 'Select address',
      'no_results_found': 'No results found',
      'map_btn_label': 'Map',
      'confirm_address_btn': 'Confirm address',
      'search_address_hint': 'Search address...',
      'selected_address_label': 'Selected address',
      'resolving_label': 'Resolving...',
      'address_not_found': 'Address not found',
      'order_details_page_title': 'Order details',
      'active_order_title': 'Active order',
      'route_label': 'Route',
      // ==== Active order page (redesign) ====
      'live_label': 'LIVE',
      'route_summary_label': 'Route Summary',
      'load_weight_label': 'Load Weight',
      'cargo_type_label': 'Cargo Type',
      'arrived_at_label': 'Arrived',
      'est_label': 'Est.',
      'estimated_arrival_label': 'Estimated arrival in {min} min',
      'traffic_light': 'Light traffic',
      'traffic_moderate': 'Moderate traffic',
      'traffic_heavy': 'Heavy traffic',
      'pickup_label': 'PICKUP',
      'dropoff_label': 'DROPOFF',
      'emergency_support_label': 'Emergency Support',
      // ==== Menu (toggle) sheet ====
      'active_order': 'Active order',
      'active_order_subtitle': 'Track your current order',
      'my_orders_subtitle': 'All your orders',
      'notifications_subtitle': 'Updates and alerts',
      'profile_subtitle': 'Personal details',
      'language_subtitle': 'Choose app language',
      'theme_subtitle': 'Customize appearance',
      'wallet_subtitle': 'Balance and transactions',
      'order_history_subtitle': 'Completed orders',
      // ==== Saved addresses ====
      'saved_places_subtitle': 'Frequently used addresses',
      'no_saved_addresses': 'No saved addresses yet',
      'add_new_address': 'Add new address',
      'edit_address': 'Edit address',
      'add_address_title': 'Add address',
      'delete': 'Delete',
      'delete_address_confirm_title': 'Delete address',
      'delete_address_confirm_msg': 'Are you sure you want to delete this address?',
      'address_name_optional_hint': 'Name (optional)',
      'address_field_hint': 'Search address or pick on map',
      'choose_on_map': 'Choose on map',
      'address_saved_snackbar': 'Address saved',
      'address_updated_snackbar': 'Address updated',
      'address_deleted_snackbar': 'Address deleted',
      'quick_save_address_title': 'Save address',
      // ==== Driver Home ====
      'online': 'Online',
      'offline': 'Offline',
      'order_waiting': 'Waiting for order',
      'you_are_online': 'You are online, wait for an order',
      'you_are_offline': 'You are offline',
      'go_online_hint': 'Go online to receive orders',
      'go_online': 'Go online',
      'new_order_label': 'NEW ORDER',
      'accept_order': 'Accept',
      'reject_order': 'Reject',
      'slide_to_accept': 'Slide to accept',
      'going_to_client': 'Going to client',
      'cargo_on_way': 'Cargo on the way',
      'picked_up_continue': 'Picked up — go',
      'delivered_finish': 'Delivered — finish',
      // ==== Driver History ====
      'view_all_history': 'View all',
      'order_history_title': 'Order history',
      'order_history_full_title': 'All orders',
      'filter_all': 'All',
      'filter_delivered': 'Delivered',
      'filter_cancelled': 'Cancelled',
      'search_city_hint': 'Search by city...',
      'no_orders_found': 'No orders found',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'status_searching': 'Searching for driver',
      'status_offered': 'Offer sent',
      'status_accepted': 'Accepted',
      'status_driver_arriving': 'Driver arriving',
      'status_loading': 'Loading',
      'status_in_transit': 'In transit',
      'status_delivered': 'Delivered',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      // ==== Order detail (history, read-only) ====
      'status_history_label': 'Status history',
      'sos_sent_label': 'SOS signal sent',
      'additional_info_label': 'Additional information',
      'distance_traveled_label': 'Distance traveled',
      'completion_duration_label': 'Completion time',
      'client_rating_label': 'Client rating',
      // ==== Order history (redesign) ====
      'trip_label': 'Trip',
      'from_label': 'From',
      'to_label': 'To',
      'filter_pending': 'Pending',
      'month_01': 'January',
      'month_02': 'February',
      'month_03': 'March',
      'month_04': 'April',
      'month_05': 'May',
      'month_06': 'June',
      'month_07': 'July',
      'month_08': 'August',
      'month_09': 'September',
      'month_10': 'October',
      'month_11': 'November',
      'month_12': 'December',
      // ==== Call / Cancel order / Avatar ====
      'call': 'Call',
      'call_confirm_title': 'Do you want to call?',
      'call_confirm_message': 'Call this number?',
      'call_failed': 'Could not place the call',
      'cancel_order_title': 'Cancel order',
      'cancel_order_message': 'Do you want to cancel the order? This may affect your rating.',
      'yes_cancel_order': 'Yes, cancel',
      'no_keep_order': 'No',
      'order_cancelled': 'Order cancelled',
      'profile_photo_optional': 'Profile photo (optional)',
      'profile_photo_hint': 'This is optional — if you don\'t upload one, a default image will be used',
      // ==== Rating dialog ====
      'rating_dialog_title': 'How was your delivery?',
      'rating_dialog_subtitle': 'Your feedback helps us maintain the quality of the GoWay logistics network',
      'review_placeholder': 'Write a review...',
      'optional_label': 'Optional',
      'submit_review': 'Submit Review',
      'skip_for_now': 'Skip for now',
      'rating_tag_on_time': 'On time',
      'rating_tag_friendly': 'Friendly',
      'rating_tag_recommend': 'Would recommend',
      'rating_submit_error': 'Couldn\'t submit your review. Please try again.',
      // ==== Profile menu (redesign) ====
      'change_password_subtitle': 'Update your security password',
      'terms_subtitle': 'Terms of use and privacy policy',
      'avatar_preview_only_notice': 'Preview only — not yet saved to the server',
      'avatar_upload_failed': 'Failed to upload photo',
    },
  };

  static String get(String key, String locale) {
    return _strings[locale]?[key] ?? _strings['uz']![key] ?? key;
  }
}