class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'uz': {
      'select_language': 'Tilni tanlang',
      'who_are_you': 'Siz kimsiz?',
      'select_role': 'Rolingizni tanlang',
      'client': 'Yuk beruvchi',
      'client_subtitle': 'Yuk tashish uchun buyurtma beraman',
      'driver': 'Haydovchi',
      'driver_subtitle': 'Yuk tashib daromad qilaman',
      'phone_title': 'Telefon raqamingiz',
      'phone_subtitle': 'SMS orqali tasdiqlash kodi yuboramiz',
      'send_code': 'Kodni yuborish',
      'enter_code': 'Kodni kiriting',
      'code_sent': 'raqamiga kod yuborildi',
      'verify': 'Tasdiqlash',
      'resend': 'Qayta yuborish',
      'resend_in': 'Qayta yuborish:',
      'skip': 'O\'tkazib yuborish',
      'next': 'Keyingi',
      'start': 'Boshlash',
      'home': 'Bosh',
      'orders': 'Buyurtmalar',
      'wallet': 'Hamyon',
      'profile': 'Profil',
      'settings': 'Sozlamalar',
      'notifications': 'Bildirishnomalar',
      'where_to': 'Qayerga yuk tashlaysiz?',
      'saved_places': 'Saqlangan manzillar',
      'tariffs': 'Tariflar',
      'full_name': 'To\'liq ism',
      'passport': 'Pasport',
      'license': 'Haydovchilik guvohnomasi',
      'tech_passport': 'Texnik pasport',
      'truck_type': 'Mashina turi',
      'plate_number': 'Davlat raqami',
      'capacity': 'Yuk ko\'tarish sig\'imi',
      'continue_btn': 'Davom etish',
      'pending_title': 'Ma\'lumotlaringiz qabul qilindi!',
      'pending_subtitle': 'Admin ko\'rib chiqib tasdiqlaydi. Bu biroz vaqt olishi mumkin.',
      'waiting': 'Kutilmoqda...',
      'onboarding1_title': 'Yuk tashish oson!',
      'onboarding1_subtitle': 'Istalgan shahardan istalgan shaharga yuk tashlang.',
      'onboarding2_title': 'Real vaqt kuzatuv',
      'onboarding2_subtitle': 'Yuk harakati xaritada real vaqtda kuzating.',
      'onboarding3_title': 'Qulay to\'lov',
      'onboarding3_subtitle': 'Hamyon orqali tez va xavfsiz to\'lov.',
      'step_sent': 'Hujjatlar yuborildi',
      'step_reviewing': 'Admin ko\'rib chiqmoqda',
      'step_approved': 'Tasdiqlash',
      'pending_time': 'Javob 5-20 daqiqa ichida beriladi',
      'edit_profile': 'Profilni tahrirlash',
      'edit': 'Tahrirlash',
      'save': 'Saqlash',
      'cancel': 'Bekor qilish',
      'close': 'Yopish',
      'confirm': 'Tasdiqlash',
      'name': 'Ism',
      'vehicle_info': 'Mashina ma\'lumotlari',
      'vehicle_edit': 'Mashina ma\'lumotlarini tahrirlash',
      'vehicle_edit_warning': 'Xavfsizlik uchun admin tasdiqlashi kerak',
      'verification_info': 'Tasdiqlanish ma\'lumotlari',
      'admin_approval_required': 'Admin tasdiqlashi talab etiladi',
      'admin_approval_sent': 'So\'rov yuborildi! Admin tasdiqlashini kuting.',
      'admin_approval_notice': 'Siz tasdiqlanish ma\'lumotlarini o\'zgartirdingiz. Xavfsizlik uchun admin tasdiqlashini kuting.',
      'change_plate': 'Davlat raqamini o\'zgartirish',
      'change_plate_subtitle': 'Yangi davlat raqami va texnik pasport talab qilinadi',
      'new_plate': 'Yangi davlat raqami',
      'upload_tech_passport': 'Texnik pasportni yuklang',
      'request_sent': 'So\'rov yuborildi',
      'request_pending': 'Admin ko\'rib chiqmoqda',
      'change_truck': 'Mashina turini o\'zgartirish',
      'documents': 'Hujjatlar',
      'uploaded': 'Yuklangan',
      'not_uploaded': 'Yuklanmagan',
      'tap_to_upload': 'Yuklash uchun bosing',
      'tap_to_change': 'O\'zgartirish uchun bosing',
      'language': 'Til',
      'theme': 'Tema',
      'theme_auto': 'Avto',
      'theme_light': 'Yorug\'',
      'theme_dark': 'Qorong\'u',
      'logout': 'Chiqish',
      'terms': 'Oferta shartlari',
      'personal_info': 'Shaxsiy ma\'lumotlar',
      'app_settings': 'Ilova sozlamalari',
      'change_password': 'Parolni o\'zgartirish',
      'current_password': 'Joriy parol',
      'new_password': 'Yangi parol',
      'confirm_password': 'Parolni tasdiqlang',
      'forgot_password': 'Parolni unutdingizmi?',
      'password_changed': 'Parol muvaffaqiyatli o\'zgartirildi',
      'password_mismatch': 'Parollar mos kelmaydi',
      'password_too_short': 'Parol kamida 6 ta belgidan iborat bo\'lishi kerak',
      'otp_sent': 'OTP kod yuborildi',
      'enter_otp': 'OTP kodni kiriting',
      'set_new_password': 'Yangi parol o\'rnating',
      'reset_password': 'Parolni tiklash',
      // ==== Client Home ====
      'menu': 'Menyu',
      'my_orders': 'Buyurtmalarim',
      'enter_address': 'Manzil kiriting',
      'place_order': 'Buyurtma berish',
      'cancel_selection': 'Bekor qilish',
      'from_question': 'Qayerdan?',
      'to_question': 'Qayerga?',
      'select_vehicle': 'Mashina turini tanlang',
      'select_truck_error': 'Iltimos, mashina turini tanlang',
      'weight_tons': 'Yuk og\'irligi (tonna)',
      'enter_weight_error': 'Og\'irlikni kiriting',
      'note_optional': 'Izoh (ixtiyoriy)',
      'generic_error': 'Xatolik yuz berdi',
      'searching_driver': 'Haydovchi qidirilmoqda...',
      'cancel_search': 'Bekor qilish',
      'driver_assigned': 'Haydovchi tayinlandi',
      'driver_arriving': 'Haydovchi kelmoqda',
      'loading_cargo': 'Yuk yuklanmoqda',
      'in_transit': 'Yuk yo\'lda',
      'delivered_msg': 'Yetkazildi! 🎉',
      'order_active': 'Buyurtma faol',
      'complete_order': 'Yakunlash',
      'select_btn': 'Tanlang',
      'route_time_min': 'daqiqa',
      'route_time_hour': 'soat',
      'arriving_in': 'yetib keladi',
      'location_permission_denied': 'Joylashuv ruxsati berilmagan — manzilni qo\'lda tanlang',
      // ==== Driver Home ====
      'online': 'Online',
      'offline': 'Offline',
      'order_waiting': 'Buyurtma kutilmoqda',
      'you_are_online': 'Siz onlinesiz, buyurtma kelishini kuting',
      'you_are_offline': 'Siz offlainesiz',
      'go_online_hint': 'Buyurtma olish uchun onlayn bo\'ling',
      'go_online': 'Online bo\'lish',
      'new_order_label': 'YANGI BUYURTMA',
      'accept_order': 'Qabul qilish',
      'reject_order': 'Rad etish',
      'going_to_client': 'Mijozga bormoqda',
      'cargo_on_way': 'Yuk yo\'lda',
      'picked_up_continue': '📦  Yuk olindi — yo\'lga chiqish',
      'delivered_finish': '✅  Yetkazildi — yakunlash',
    },
    'ru': {
      'select_language': 'Выберите язык',
      'who_are_you': 'Кто вы?',
      'select_role': 'Выберите роль',
      'client': 'Грузоотправитель',
      'client_subtitle': 'Заказываю перевозку грузов',
      'driver': 'Водитель',
      'driver_subtitle': 'Перевожу грузы и зарабатываю',
      'phone_title': 'Ваш номер телефона',
      'phone_subtitle': 'Отправим код подтверждения по SMS',
      'send_code': 'Отправить код',
      'enter_code': 'Введите код',
      'code_sent': 'код отправлен на номер',
      'verify': 'Подтвердить',
      'resend': 'Отправить снова',
      'resend_in': 'Повторная отправка:',
      'skip': 'Пропустить',
      'next': 'Далее',
      'start': 'Начать',
      'home': 'Главная',
      'orders': 'Заказы',
      'wallet': 'Кошелёк',
      'profile': 'Профиль',
      'settings': 'Настройки',
      'notifications': 'Уведомления',
      'where_to': 'Куда отправить груз?',
      'saved_places': 'Сохранённые места',
      'tariffs': 'Тарифы',
      'full_name': 'Полное имя',
      'passport': 'Паспорт',
      'license': 'Водительское удостоверение',
      'tech_passport': 'Техпаспорт',
      'truck_type': 'Тип грузовика',
      'plate_number': 'Гос. номер',
      'capacity': 'Грузоподъёмность',
      'continue_btn': 'Продолжить',
      'pending_title': 'Данные приняты!',
      'pending_subtitle': 'Администратор рассмотрит и подтвердит.',
      'waiting': 'Ожидание...',
      'onboarding1_title': 'Перевозка проста!',
      'onboarding1_subtitle': 'Перевозите грузы из любого города в любой.',
      'onboarding2_title': 'Отслеживание в реальном времени',
      'onboarding2_subtitle': 'Следите за грузом на карте в реальном времени.',
      'onboarding3_title': 'Удобная оплата',
      'onboarding3_subtitle': 'Быстрая и безопасная оплата через кошелёк.',
      'step_sent': 'Документы отправлены',
      'step_reviewing': 'Администратор проверяет',
      'step_approved': 'Подтверждение',
      'pending_time': 'Ответ будет дан в течение 5-20 минут',
      'edit_profile': 'Редактировать профиль',
      'edit': 'Изменить',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'close': 'Закрыть',
      'confirm': 'Подтвердить',
      'name': 'Имя',
      'vehicle_info': 'Данные автомобиля',
      'vehicle_edit': 'Редактировать данные авто',
      'vehicle_edit_warning': 'Требуется подтверждение администратора',
      'verification_info': 'Данные верификации',
      'admin_approval_required': 'Требуется подтверждение администратора',
      'admin_approval_sent': 'Запрос отправлен! Ожидайте подтверждения.',
      'admin_approval_notice': 'Вы изменили данные верификации. В целях безопасности ожидайте подтверждения администратора.',
      'change_plate': 'Изменить гос. номер',
      'change_plate_subtitle': 'Требуется новый номер и техпаспорт',
      'new_plate': 'Новый гос. номер',
      'upload_tech_passport': 'Загрузите техпаспорт',
      'request_sent': 'Запрос отправлен',
      'request_pending': 'Администратор проверяет',
      'change_truck': 'Изменить тип грузовика',
      'documents': 'Документы',
      'uploaded': 'Загружено',
      'not_uploaded': 'Не загружено',
      'tap_to_upload': 'Нажмите для загрузки',
      'tap_to_change': 'Нажмите для изменения',
      'language': 'Язык',
      'theme': 'Тема',
      'theme_auto': 'Авто',
      'theme_light': 'Светлая',
      'theme_dark': 'Тёмная',
      'logout': 'Выйти',
      'terms': 'Условия оферты',
      'personal_info': 'Личные данные',
      'app_settings': 'Настройки приложения',
      'change_password': 'Изменить пароль',
      'current_password': 'Текущий пароль',
      'new_password': 'Новый пароль',
      'confirm_password': 'Подтвердите пароль',
      'forgot_password': 'Забыли пароль?',
      'password_changed': 'Пароль успешно изменён',
      'password_mismatch': 'Пароли не совпадают',
      'password_too_short': 'Пароль должен содержать минимум 6 символов',
      'otp_sent': 'OTP код отправлен',
      'enter_otp': 'Введите OTP код',
      'set_new_password': 'Установите новый пароль',
      'reset_password': 'Восстановить пароль',
      // ==== Client Home ====
      'menu': 'Меню',
      'my_orders': 'Мои заказы',
      'enter_address': 'Введите адрес',
      'place_order': 'Оформить заказ',
      'cancel_selection': 'Отмена',
      'from_question': 'Откуда?',
      'to_question': 'Куда?',
      'select_vehicle': 'Выберите тип автомобиля',
      'select_truck_error': 'Пожалуйста, выберите тип автомобиля',
      'weight_tons': 'Вес груза (тонн)',
      'enter_weight_error': 'Введите вес',
      'note_optional': 'Комментарий (необязательно)',
      'generic_error': 'Произошла ошибка',
      'searching_driver': 'Поиск водителя...',
      'cancel_search': 'Отмена',
      'driver_assigned': 'Водитель назначен',
      'driver_arriving': 'Водитель едет',
      'loading_cargo': 'Загрузка груза',
      'in_transit': 'Груз в пути',
      'delivered_msg': 'Доставлено! 🎉',
      'order_active': 'Заказ активен',
      'complete_order': 'Завершить',
      'select_btn': 'Выбрать',
      'route_time_min': 'мин',
      'route_time_hour': 'ч',
      'arriving_in': 'приедет через',
      'location_permission_denied': 'Доступ к геолокации не предоставлен — выберите адрес вручную',
      // ==== Driver Home ====
      'online': 'Онлайн',
      'offline': 'Оффлайн',
      'order_waiting': 'Ожидание заказа',
      'you_are_online': 'Вы онлайн, ожидайте заказ',
      'you_are_offline': 'Вы оффлайн',
      'go_online_hint': 'Включите онлайн для получения заказов',
      'go_online': 'Включить онлайн',
      'new_order_label': 'НОВЫЙ ЗАКАЗ',
      'accept_order': 'Принять',
      'reject_order': 'Отклонить',
      'going_to_client': 'Едет к клиенту',
      'cargo_on_way': 'Груз в пути',
      'picked_up_continue': '📦  Груз забран — в путь',
      'delivered_finish': '✅  Доставлено — завершить',
    },
    'en': {
      'select_language': 'Choose language',
      'who_are_you': 'Who are you?',
      'select_role': 'Select your role',
      'client': 'Cargo Sender',
      'client_subtitle': 'I order cargo transportation',
      'driver': 'Driver',
      'driver_subtitle': 'I transport cargo and earn',
      'phone_title': 'Your phone number',
      'phone_subtitle': 'We will send a verification code via SMS',
      'send_code': 'Send code',
      'enter_code': 'Enter code',
      'code_sent': 'code sent to',
      'verify': 'Verify',
      'resend': 'Resend',
      'resend_in': 'Resend in:',
      'skip': 'Skip',
      'next': 'Next',
      'start': 'Get started',
      'home': 'Home',
      'orders': 'Orders',
      'wallet': 'Wallet',
      'profile': 'Profile',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'where_to': 'Where to send cargo?',
      'saved_places': 'Saved places',
      'tariffs': 'Tariffs',
      'full_name': 'Full name',
      'passport': 'Passport',
      'license': 'Driver\'s license',
      'tech_passport': 'Tech passport',
      'truck_type': 'Truck type',
      'plate_number': 'Plate number',
      'capacity': 'Load capacity',
      'continue_btn': 'Continue',
      'pending_title': 'Your data has been received!',
      'pending_subtitle': 'Admin will review and approve.',
      'waiting': 'Waiting...',
      'onboarding1_title': 'Easy cargo delivery!',
      'onboarding1_subtitle': 'Transport cargo from any city to any city.',
      'onboarding2_title': 'Real-time tracking',
      'onboarding2_subtitle': 'Track cargo on the map in real time.',
      'onboarding3_title': 'Easy payment',
      'onboarding3_subtitle': 'Fast and secure payment via wallet.',
      'step_sent': 'Documents submitted',
      'step_reviewing': 'Admin is reviewing',
      'step_approved': 'Approval',
      'pending_time': 'Response will be given within 5-20 minutes',
      'edit_profile': 'Edit profile',
      'edit': 'Edit',
      'save': 'Save',
      'cancel': 'Cancel',
      'close': 'Close',
      'confirm': 'Confirm',
      'name': 'Name',
      'vehicle_info': 'Vehicle info',
      'vehicle_edit': 'Edit vehicle info',
      'vehicle_edit_warning': 'Admin approval required',
      'verification_info': 'Verification info',
      'admin_approval_required': 'Admin approval required',
      'admin_approval_sent': 'Request sent! Waiting for admin approval.',
      'admin_approval_notice': 'You changed verification data. For security, please wait for admin approval.',
      'change_plate': 'Change plate number',
      'change_plate_subtitle': 'New plate and tech passport required',
      'new_plate': 'New plate number',
      'upload_tech_passport': 'Upload tech passport',
      'request_sent': 'Request sent',
      'request_pending': 'Admin is reviewing',
      'change_truck': 'Change truck type',
      'documents': 'Documents',
      'uploaded': 'Uploaded',
      'not_uploaded': 'Not uploaded',
      'tap_to_upload': 'Tap to upload',
      'tap_to_change': 'Tap to change',
      'language': 'Language',
      'theme': 'Theme',
      'theme_auto': 'Auto',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'logout': 'Logout',
      'terms': 'Terms of service',
      'personal_info': 'Personal info',
      'app_settings': 'App settings',
      'change_password': 'Change password',
      'current_password': 'Current password',
      'new_password': 'New password',
      'confirm_password': 'Confirm password',
      'forgot_password': 'Forgot password?',
      'password_changed': 'Password changed successfully',
      'password_mismatch': 'Passwords do not match',
      'password_too_short': 'Password must be at least 6 characters',
      'otp_sent': 'OTP code sent',
      'enter_otp': 'Enter OTP code',
      'set_new_password': 'Set new password',
      'reset_password': 'Reset password',
      // ==== Client Home ====
      'menu': 'Menu',
      'my_orders': 'My orders',
      'enter_address': 'Enter address',
      'place_order': 'Place order',
      'cancel_selection': 'Cancel',
      'from_question': 'From?',
      'to_question': 'To?',
      'select_vehicle': 'Select vehicle type',
      'select_truck_error': 'Please select a vehicle type',
      'weight_tons': 'Cargo weight (tons)',
      'enter_weight_error': 'Enter weight',
      'note_optional': 'Note (optional)',
      'generic_error': 'An error occurred',
      'searching_driver': 'Searching for driver...',
      'cancel_search': 'Cancel',
      'driver_assigned': 'Driver assigned',
      'driver_arriving': 'Driver is arriving',
      'loading_cargo': 'Loading cargo',
      'in_transit': 'Cargo in transit',
      'delivered_msg': 'Delivered! 🎉',
      'order_active': 'Order active',
      'complete_order': 'Complete',
      'select_btn': 'Select',
      'route_time_min': 'min',
      'route_time_hour': 'h',
      'arriving_in': 'arriving in',
      'location_permission_denied': 'Location permission denied — please select address manually',
      // ==== Driver Home ====
      'online': 'Online',
      'offline': 'Offline',
      'order_waiting': 'Waiting for order',
      'you_are_online': 'You are online, wait for an order',
      'you_are_offline': 'You are offline',
      'go_online_hint': 'Go online to receive orders',
      'go_online': 'Go online',
      'new_order_label': 'NEW ORDER',
      'accept_order': 'Accept',
      'reject_order': 'Reject',
      'going_to_client': 'Going to client',
      'cargo_on_way': 'Cargo on the way',
      'picked_up_continue': '📦  Picked up — go',
      'delivered_finish': '✅  Delivered — finish',
    },
  };

  static String get(String key, String locale) {
    return _strings[locale]?[key] ?? _strings['uz']![key] ?? key;
  }
}